import{z}from'zod';import{getSession}from'../../../lib/auth';import{withTenant}from'../../../lib/db';import{nextStoreReference}from'../../../lib/document-references';
const schema=z.object({itemId:z.string().uuid(),lotNumber:z.string().optional(),expiryDate:z.string().optional(),countedQuantity:z.coerce.number().nonnegative()});
export async function POST(r:Request){const s=await getSession();if(!s)return Response.redirect(new URL('/signin',r.url),303);const p=schema.safeParse(Object.fromEntries(await r.formData()));if(!p.success)return Response.redirect(new URL('/store-portal/counts?error=1',r.url),303);try{const reference=await withTenant(s.companyId,async c=>{
  const a=(await c.query<{store_id:string;code:string}>(`SELECT a.store_id,x.code FROM store_user_assignments a JOIN requesting_stores x ON x.company_id=a.company_id AND x.id=a.store_id WHERE a.company_id=$1 AND a.user_id=$2 AND a.store_role IN('store_operator','store_manager')`,[s.companyId,s.userId])).rows[0];if(!a)throw new Error();
  const item=(await c.query(`SELECT base_uom FROM items WHERE company_id=$1 AND id=$2 AND status='active'`,[s.companyId,p.data.itemId])).rows[0];if(!item)throw new Error();
  const system=Number((await c.query(`SELECT coalesce(sum(quantity),0) q FROM store_inventory_ledger WHERE company_id=$1 AND store_id=$2 AND item_id=$3 AND lot_number IS NOT DISTINCT FROM $4 AND expiry_date IS NOT DISTINCT FROM $5::date`,[s.companyId,a.store_id,p.data.itemId,p.data.lotNumber||null,p.data.expiryDate||null])).rows[0].q),countNo=await nextStoreReference(c,{companyId:s.companyId,storeId:a.store_id,storeCode:a.code,documentType:'store_count'});
  const count=(await c.query(`INSERT INTO store_inventory_counts(company_id,store_id,count_no,submitted_by) VALUES($1,$2,$3,$4) RETURNING id`,[s.companyId,a.store_id,countNo,s.userId])).rows[0];
  await c.query(`INSERT INTO store_inventory_count_lines(company_id,count_id,item_id,lot_number,expiry_date,system_quantity,counted_quantity,uom) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[s.companyId,count.id,p.data.itemId,p.data.lotNumber||null,p.data.expiryDate||null,system,p.data.countedQuantity,item.base_uom]);
  await c.query(`INSERT INTO audit_logs(company_id,user_id,action,entity_type,entity_id,details) VALUES($1,$2,'store_count_submitted','store_inventory_count',$3,$4::jsonb)`,[s.companyId,s.userId,count.id,JSON.stringify({reference:countNo})]);return countNo});
  return Response.redirect(new URL(`/store-portal/counts?submitted=1&reference=${encodeURIComponent(reference)}`,r.url),303)}catch{return Response.redirect(new URL('/store-portal/counts?error=1',r.url),303)}}
