import Link from "next/link";
import { getSession } from "../../../../lib/auth";
import { tenantRows } from "../../../../lib/db";
export const metadata={title:'Transfer stock'};export const dynamic='force-dynamic';
type Item={id:string;sku:string;description:string;base_uom:string};type Location={id:string;code:string;warehouse:string};
const messages:Record<string,string>={insufficient_stock:'The source location does not have enough matching stock.',uom_mismatch:'Use the item base unit for this transfer.',invalid_scope:'The selected item or location is not available.',invalid:'Check all required transfer fields.'};
export default async function Transfer({searchParams}:{searchParams:Promise<{error?:string}>}){
  const session=await getSession();const {error}=await searchParams;
  const items=session?await tenantRows<Item>(session.companyId,`SELECT id,sku,description,base_uom FROM items WHERE company_id=$1 AND status='active' ORDER BY sku`,[session.companyId]):[];
  const locations=session?await tenantRows<Location>(session.companyId,`SELECT l.id,l.code,w.name AS warehouse FROM locations l JOIN warehouses w ON w.company_id=l.company_id AND w.id=l.warehouse_id WHERE l.company_id=$1 AND l.active=true ORDER BY w.name,l.code`,[session.companyId]):[];
  return <div className="app-content"><div className="page-heading"><div><h1>Transfer stock</h1><p>Move inventory between locations using a balanced ledger transaction.</p></div><Link href="/app/inventory" className="button button-secondary">Cancel</Link></div>{error&&<div className="form-error">{messages[error]||'The transfer could not be posted.'}</div>}<div className="form-layout"><form className="panel form-section" method="post" action="/api/inventory/transfer"><h2>Transfer details</h2><div className="field"><label htmlFor="itemId">Item</label><select id="itemId" name="itemId" required>{items.map(item=><option key={item.id} value={item.id}>{item.sku} — {item.description} ({item.base_uom})</option>)}</select></div><div className="form-row"><div className="field"><label htmlFor="fromLocationId">From location</label><select id="fromLocationId" name="fromLocationId" required>{locations.map(location=><option key={location.id} value={location.id}>{location.warehouse} · {location.code}</option>)}</select></div><div className="field"><label htmlFor="toLocationId">To location</label><select id="toLocationId" name="toLocationId" required>{locations.map(location=><option key={location.id} value={location.id}>{location.warehouse} · {location.code}</option>)}</select></div></div><div className="form-row"><div className="field"><label htmlFor="quantity">Quantity</label><input id="quantity" name="quantity" type="number" min="0.000001" step="any" required/></div><div className="field"><label htmlFor="uom">Base unit</label><input id="uom" name="uom" placeholder="EA" required/></div></div><div className="form-row"><div className="field"><label htmlFor="lotNumber">Lot number</label><input id="lotNumber" name="lotNumber" placeholder="Optional"/></div><div className="field"><label htmlFor="expiryDate">Expiry date</label><input id="expiryDate" name="expiryDate" type="date"/></div></div><div className="field"><label htmlFor="referenceId">Reference</label><input id="referenceId" name="referenceId" placeholder="TR-0001" required/></div><div className="field"><label htmlFor="note">Note</label><textarea id="note" name="note" rows={3}/></div><button className="button button-primary" type="submit">Post transfer</button></form><aside className="panel"><h2>Transfer controls</h2><ul className="help-list"><li>Source and destination post together or not at all.</li><li>The source balance cannot become negative.</li><li>Lot and expiry values must match the source balance.</li><li>Both movements share one traceable transaction reference.</li></ul></aside></div></div>
}
