import Link from 'next/link';import {redirect} from 'next/navigation';import {getSession} from '../../lib/auth';import {db} from '../../lib/db';export const dynamic='force-dynamic';type NavLink=[string,string,string];
const groups:{label:string;links:NavLink[]}[]=[
{label:'Overview',links:[['/app/dashboard','⌂','Dashboard'],['/app/approvals','✓','Approvals'],['/app/exceptions','!','Exceptions']]},
{label:'Master data',links:[['/app/items','□','Item master'],['/app/setup','⌘','Warehouse setup']]},
{label:'Inbound',links:[['/app/purchasing','▤','Purchase orders'],['/app/purchasing/import','↥','PO import'],['/app/docks','⇥','Dock scheduling'],['/app/docks/mobile','▣','Gate check-in'],['/app/receiving','⇩','Receiving'],['/app/receiving/mobile','▣','Mobile receiving'],['/app/putaway/mobile','↳','Mobile putaway'],['/app/cross-dock','⇥','Cross-docking']]},
{label:'Inventory',links:[['/app/inventory','⇄','Inventory balances'],['/app/counts','✓','Stock counts'],['/app/replenishment','↻','Replenishment'],['/app/forecasting','⌁','Forecasting'],['/app/traceability','◎','Traceability'],['/app/returns','↩','Returns']]},
{label:'Outbound',links:[['/app/orders','⇧','Orders & picking'],['/app/waves','≋','Pick waves'],['/app/fulfillment/mobile','▣','Mobile pick & pack'],['/app/packing/cartons','▢','Packing cartons'],['/app/dispatch/mobile','⇱','Mobile dispatch'],['/app/dispatch-reversals','↶','Dispatch reversals'],['/app/manifests','☷','Shipping manifests']]},
{label:'Operations',links:[['/app/labor','♙','Labor & productivity']]},
{label:'Insights',links:[['/app/reports','▥','Reports'],['/app/report-automation','◷','Report automation'],['/app/delivery-history','!','Alerts & delivery']]},
{label:'Administration',links:[['/app/integrations','⌁','ERP integrations'],['/app/users','♙','Users & access'],['/app/company','⚙','Company & plan'],['/app/billing','₱','Subscription & billing'],['/account/security','⚿','Account security']]}
];
export default async function AppLayout({children}:{children:React.ReactNode}){const session=await getSession();if(!session)redirect('/signin');if(session.mustChangePassword)redirect('/account/password');const company=(await db().query<{name:string;access_status:string;subscription_ends_at:string|null}>('SELECT name,access_status,subscription_ends_at::text FROM companies WHERE id=$1',[session.companyId])).rows[0];if(!company||company.access_status==='frozen'||(company.subscription_ends_at&&Date.parse(company.subscription_ends_at)<Date.now()))redirect('/access-suspended');const initials=session.email.slice(0,2).toUpperCase();return <div className="app-shell"><aside className="sidebar"><Link href="/app/dashboard" className="brand"><span className="brand-mark">W</span><span>Warevanta</span></Link><div className="company-chip"><small>COMPANY SPACE</small><strong>{company.name}</strong></div><nav className="app-nav" aria-label="Warehouse applications">{groups.map(group=><section className="nav-group" key={group.label}><h2>{group.label}</h2>{group.links.map(([href,icon,label])=><Link key={href} href={href} aria-label={label}><i aria-hidden="true">{icon}</i><span>{label}</span></Link>)}</section>)}</nav><div className="sidebar-foot"><form method="post" action="/api/auth/signout"><button className="signout-button" type="submit">Sign out</button></form><br/>Tenant-isolated workspace</div></aside><main className="app-main"><header className="app-topbar"><div className="warehouse-title"><strong>Main Warehouse</strong><small>{company.name}</small></div><div className="user-avatar" aria-label={session.email}>{initials}</div></header>{children}</main></div>}
