"use client";
import { useEffect,useRef,useState } from "react";
type InstallEvent=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>};
export default function MobileRuntime(){const [online,setOnline]=useState(true);const [install,setInstall]=useState<InstallEvent|null>(null);const [scanning,setScanning]=useState(false);const [message,setMessage]=useState('Point the camera at a barcode');const video=useRef<HTMLVideoElement>(null);const target=useRef<HTMLInputElement|null>(null);const stream=useRef<MediaStream|null>(null);
  useEffect(()=>{setOnline(navigator.onLine);const on=()=>setOnline(true),off=()=>setOnline(false),before=(e:Event)=>{e.preventDefault();setInstall(e as InstallEvent)};addEventListener('online',on);addEventListener('offline',off);addEventListener('beforeinstallprompt',before);if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>undefined);
    const enhance=()=>document.querySelectorAll<HTMLInputElement>('input[name="barcode"],input[name="locationCode"]').forEach(input=>{if(input.dataset.mobileScan)return;input.dataset.mobileScan='1';const form=input.form;const key=`stockflow-draft:${form?.getAttribute('action')||location.pathname}:${input.name}`;const saved=localStorage.getItem(key);if(saved&&!input.value)input.value=saved;input.addEventListener('input',()=>localStorage.setItem(key,input.value));form?.addEventListener('submit',()=>{if(navigator.onLine)localStorage.removeItem(key)},{once:true});const button=document.createElement('button');button.type='button';button.className='button button-secondary camera-scan-button';button.textContent='📷 Scan with camera';button.setAttribute('aria-label',`Scan ${input.name} with phone camera`);button.onclick=()=>start(input);input.insertAdjacentElement('afterend',button)});enhance();const observer=new MutationObserver(enhance);observer.observe(document.body,{childList:true,subtree:true});return()=>{removeEventListener('online',on);removeEventListener('offline',off);removeEventListener('beforeinstallprompt',before);observer.disconnect();stop()}} ,[]);
  async function start(input:HTMLInputElement){target.current=input;setMessage('Point the camera at a barcode');if(!('BarcodeDetector'in window)){setMessage('Camera decoding is not supported by this browser. Use the manual field or a Bluetooth scanner.');setScanning(true);return}try{stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});setScanning(true);setTimeout(()=>{if(video.current&&stream.current){video.current.srcObject=stream.current;video.current.play();detect()}},50)}catch{setMessage('Camera access was not allowed. Enable camera permission or enter the code manually.');setScanning(true)}}
  async function detect(){if(!video.current||!stream.current)return;try{const Detector=(window as any).BarcodeDetector;const detector=new Detector({formats:['code_128','ean_13','ean_8','upc_a','upc_e','qr_code','data_matrix']});const codes=await detector.detect(video.current);if(codes[0]?.rawValue&&target.current){target.current.value=codes[0].rawValue;target.current.dispatchEvent(new Event('input',{bubbles:true}));navigator.vibrate?.(120);beep();setMessage(`Scanned: ${codes[0].rawValue}`);setTimeout(stop,450);return}}catch{}requestAnimationFrame(detect)}
  function beep(){try{const Audio=(window.AudioContext||(window as any).webkitAudioContext);const ctx=new Audio();const osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=880;gain.gain.value=.08;osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.1)}catch{}}
  function stop(){stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;setScanning(false)}
  return <><div className={`connectivity-pill ${online?'online':'offline'}`} role="status">{online?'● Online':'● Offline · scans saved on this phone'}</div>{install&&<button className="install-app-button" onClick={async()=>{await install.prompt();setInstall(null)}}>Install StockFlow</button>}{scanning&&<div className="scanner-modal" role="dialog" aria-modal="true" aria-label="Barcode camera scanner"><div className="scanner-card"><div className="scanner-frame"><video ref={video} playsInline muted/><span/></div><p>{message}</p><button className="button button-secondary" onClick={stop}>Close scanner</button></div></div>}</>}
