import Link from 'next/link';
import { getSession } from '../../../lib/auth';
import { tenantRows } from '../../../lib/db';

export const metadata = { title: 'Order orchestration' };
export const dynamic = 'force-dynamic';

type Order = { id:string; order_no:string; customer:string; store_code:string|null; status:string; requested_ship_date:string|null; lines:string };
type Warehouse = { id:string; name:string };
type Item = { id:string; sku:string; description:string; base_uom:string };
type Store = { id:string; code:string; name:string };
type Control = { pending_requests:string; open_exceptions:string; overdue_exceptions:string; allocation_failures:string };

export default async function Orders({ searchParams }:{ searchParams:Promise<{error?:string}> }) {
  const session = await getSession();
  const { error } = await searchParams;
  const [orders, warehouses, items, stores, controls] = session ? await Promise.all([
    tenantRows<Order>(session.companyId, `SELECT o.id,o.order_no,o.customer,x.code AS store_code,o.status,o.requested_ship_date::text,string_agg(i.sku||' × '||ol.ordered_quantity::text||' '||ol.uom,', ') AS lines FROM sales_orders o JOIN sales_order_lines ol ON ol.order_id=o.id JOIN items i ON i.id=ol.item_id LEFT JOIN requesting_stores x ON x.id=o.store_id AND x.company_id=o.company_id WHERE o.company_id=$1 AND (o.store_id IS NULL OR (o.store_approval_status='approved' AND o.warehouse_review_status='accepted')) AND ($2='owner' OR EXISTS(SELECT 1 FROM user_warehouse_assignments a WHERE a.company_id=o.company_id AND a.user_id=$3 AND a.warehouse_id=o.warehouse_id)) GROUP BY o.id,x.code ORDER BY o.created_at DESC`, [session.companyId,session.role,session.userId]),
    tenantRows<Warehouse>(session.companyId, `SELECT w.id,w.name FROM warehouses w WHERE w.company_id=$1 AND w.active=true AND ($2='owner' OR EXISTS(SELECT 1 FROM user_warehouse_assignments a WHERE a.company_id=w.company_id AND a.user_id=$3 AND a.warehouse_id=w.id))`, [session.companyId,session.role,session.userId]),
    tenantRows<Item>(session.companyId, `SELECT id,sku,description,base_uom FROM items WHERE company_id=$1 AND status='active' ORDER BY sku`, [session.companyId]),
    tenantRows<Store>(session.companyId, `SELECT id,code,name FROM requesting_stores WHERE company_id=$1 AND status='active' ORDER BY name`, [session.companyId]),
    tenantRows<Control>(session.companyId, `SELECT (SELECT count(*) FROM sales_orders o WHERE o.company_id=$1 AND o.store_approval_status='approved' AND o.warehouse_review_status='pending' AND ($2='owner' OR EXISTS(SELECT 1 FROM user_warehouse_assignments a WHERE a.company_id=o.company_id AND a.user_id=$3 AND a.warehouse_id=o.warehouse_id)))::text pending_requests,(SELECT count(*) FROM operational_exceptions e WHERE e.company_id=$1 AND e.status<>'resolved' AND ($2='owner' OR EXISTS(SELECT 1 FROM user_warehouse_assignments a WHERE a.company_id=e.company_id AND a.user_id=$3 AND a.warehouse_id=e.warehouse_id)))::text open_exceptions,(SELECT count(*) FROM operational_exceptions e WHERE e.company_id=$1 AND e.status<>'resolved' AND e.sla_due_at<now() AND ($2='owner' OR EXISTS(SELECT 1 FROM user_warehouse_assignments a WHERE a.company_id=e.company_id AND a.user_id=$3 AND a.warehouse_id=e.warehouse_id)))::text overdue_exceptions,(SELECT count(*) FROM replenishment_allocation_jobs j WHERE j.company_id=$1 AND j.status='exception' AND ($2='owner' OR EXISTS(SELECT 1 FROM user_warehouse_assignments a WHERE a.company_id=j.company_id AND a.user_id=$3 AND a.warehouse_id=j.warehouse_id)))::text allocation_failures`, [session.companyId,session.role,session.userId])
  ]) : [[],[],[],[],[]];
  const control = controls[0] || { pending_requests:'0', open_exceptions:'0', overdue_exceptions:'0', allocation_failures:'0' };
  const activeOrders = orders.filter(order => !['dispatched','cancelled'].includes(order.status));
  const blockedOrders = orders.filter(order => ['held','backordered'].includes(order.status));

  return <div className="app-content">
    <div className="page-heading"><div><h1>Order orchestration</h1><p>See demand, fulfillment progress, and exceptions before acting on individual orders.</p></div><div className="form-row"><Link className="button button-primary" href="/app/stores/requests">Store request queue</Link><Link className="button button-secondary" href="/app/orders/operations-control">Operations control</Link></div></div>
    {error && <div className="form-error">The order could not be created. Select an active store and check the order details.</div>}
    <section className="store-kpis"><article><small>ACTIVE ORDERS</small><strong>{activeOrders.length}</strong><p>Released and not completed</p></article><article><small>PENDING STORE REQUESTS</small><strong>{control.pending_requests}</strong><p>Awaiting warehouse review</p></article><article><small>BLOCKED ORDERS</small><strong>{blockedOrders.length}</strong><p>Held or backordered</p></article><article><small>OPEN EXCEPTIONS</small><strong>{control.open_exceptions}</strong><p>{control.overdue_exceptions} overdue · {control.allocation_failures} allocation failures</p></article></section>
    <div className="form-layout">
      <section className="panel"><h2>Fulfillment work queue</h2><table className="data-table"><thead><tr><th>Order</th><th>Requesting store</th><th>Lines</th><th>Ship date</th><th>Status</th></tr></thead><tbody>{orders.length ? orders.map(order => <tr key={order.id}><td><Link className="table-link" href={`/app/orders/${order.id}`}>{order.order_no}</Link></td><td>{order.store_code && <small>{order.store_code}</small>}{order.customer}</td><td>{order.lines}</td><td>{order.requested_ship_date || '—'}</td><td><span className="badge">{order.status}</span></td></tr>) : <tr><td className="empty-cell" colSpan={5}>No released outbound orders yet.</td></tr>}</tbody></table></section>
      <aside className="panel"><h2>Create warehouse order</h2>{!stores.length && <div className="knowledge-note">Create an active requesting store first, or enter a legacy customer name below.</div>}<form className="form-stack compact-form" method="post" action="/api/orders"><div className="field"><label>Order number</label><input name="orderNo" placeholder="SO-0001" required/></div><div className="field"><label>Requesting store</label><select name="storeId" defaultValue=""><option value="">Legacy / external customer</option>{stores.map(store => <option key={store.id} value={store.id}>{store.code} — {store.name}</option>)}</select></div><div className="field"><label>Customer name (only when no store is selected)</label><input name="customer"/></div><div className="field"><label>Fulfilling warehouse</label><select name="warehouseId">{warehouses.map(warehouse => <option key={warehouse.id} value={warehouse.id}>{warehouse.name}</option>)}</select></div><div className="field"><label>Item</label><select name="itemId">{items.map(item => <option key={item.id} value={item.id}>{item.sku} — {item.description}</option>)}</select></div><div className="form-row"><div className="field"><label>Quantity</label><input name="quantity" type="number" min="0.000001" step="any" required/></div><div className="field"><label>Unit</label><input name="uom" defaultValue={items[0]?.base_uom || 'EA'} required/></div></div><div className="form-row"><div className="field"><label>Requested ship date</label><input name="requestedShipDate" type="date"/></div><div className="field"><label>Priority</label><select name="priority" defaultValue="normal"><option>low</option><option>normal</option><option>high</option><option>urgent</option></select></div></div><button className="button button-primary">Create order</button></form></aside>
    </div>
  </div>;
}
