import {getSession} from '../../../../lib/auth';
import {tenantRows} from '../../../../lib/db';
export const dynamic='force-dynamic';
type Task={id:string;sku:string;description:string;quantity:string;uom:string;from_code:string;to_code:string};

export default async function MobilePutaway({searchParams}:{searchParams:Promise<{error?:string}>}){
  const s=await getSession();const q=await searchParams;
  const tasks=s?await tenantRows<Task>(s.companyId,`SELECT t.id,i.sku,i.description,t.quantity::text,t.uom,f.code AS from_code,d.code AS to_code FROM putaway_tasks t JOIN items i ON i.id=t.item_id JOIN locations f ON f.id=t.from_location_id JOIN locations d ON d.id=t.to_location_id WHERE t.company_id=$1 AND t.status='pending' AND ($2='owner' OR EXISTS(SELECT 1 FROM user_warehouse_assignments a WHERE a.company_id=t.company_id AND a.user_id=$3 AND a.warehouse_id=f.warehouse_id)) ORDER BY t.created_at`,[s.companyId,s.role,s.userId]):[];
  const error=q.error==='access'?'You are not assigned to that putaway task’s warehouse. Ask an Owner or Administrator to update Users and access.':q.error?'Scans did not match the assigned putaway task.':null;
  return <div className="app-content"><div className="page-heading"><div><h1>Mobile putaway</h1><p>Scan source, item, and destination before moving received stock.</p></div></div>{error&&<div className="form-error">{error}</div>}<section className="panel">{tasks.length?tasks.map(t=><article className="pick-card" key={t.id}><div><strong>{t.quantity} {t.uom} · {t.sku}</strong><small>{t.description}</small><small>{t.from_code} → {t.to_code}</small></div><form className="form-stack" method="post" action={`/api/putaway/${t.id}/mobile-confirm`}><div className="field"><label>Source location</label><input name="locationCode" placeholder={t.from_code} required/></div><div className="field"><label>Item barcode</label><input name="barcode" placeholder="Scan item" required/></div><div className="field"><label>Destination location</label><input name="destinationCode" placeholder={t.to_code} required/></div><button className="button button-primary">Confirm putaway</button></form></article>):<p className="empty-cell">No pending putaway tasks in your assigned warehouses.</p>}</section></div>;
}
