import{getSession}from'../../../lib/auth';import{withTenant}from'../../../lib/db';import{nextStoreReference}from'../../../lib/document-references';import{notifyStoreManagers}from'../../../lib/store-notifications';import{z}from'zod';
const schema=z.object({itemId:z.string().uuid(),quantity:z.coerce.number().positive().max(999999999),requestedShipDate:z.string().optional()});
export async function POST(r:Request){const s=await getSession();if(!s)return Response.redirect(new URL('/signin?returnTo=/store-portal',r.url),303);const p=schema.safeParse(Object.fromEntries(await r.formData()));if(!p.success)return Response.redirect(new URL('/store-portal?error=request-invalid',r.url),303);let stage='tenant';try{const reference=await withTenant(s.companyId,async c=>{
  stage='access';const context=(await c.query<{store_id:string;name:string;code:string;warehouse_id:string|null}>(`SELECT a.store_id,x.name,x.code,w.id AS warehouse_id FROM store_user_assignments AS a JOIN requesting_stores AS x ON x.company_id=a.company_id AND x.id=a.store_id AND x.status='active' LEFT JOIN warehouses AS w ON w.company_id=x.company_id AND w.id=x.default_warehouse_id AND w.active WHERE a.company_id=$1 AND a.user_id=$2 AND a.store_role IN('store_operator','store_manager')`,[s.companyId,s.userId])).rows[0];if(!context)throw new Error('STORE_ACCESS');if(!context.warehouse_id)throw new Error('WAREHOUSE');
  stage='item';const item=(await c.query<{base_uom:string}>(`SELECT i.base_uom FROM items AS i WHERE i.company_id=$1 AND i.id=$2 AND i.status='active'`,[s.companyId,p.data.itemId])).rows[0];if(!item)throw new Error('ITEM');
  stage='reference';const orderNo=await nextStoreReference(c,{companyId:s.companyId,storeId:context.store_id,storeCode:context.code,documentType:'store_request'});
  stage='order';const o=(await c.query<{id:string}>(`INSERT INTO sales_orders(company_id,warehouse_id,store_id,order_no,customer,requested_ship_date,priority,created_by,store_approval_status) VALUES($1,$2,$3,$4,$5,$6,'normal',$7,'pending') RETURNING sales_orders.id`,[s.companyId,context.warehouse_id,context.store_id,orderNo,context.name,p.data.requestedShipDate||null,s.userId])).rows[0];
  stage='line';await c.query(`INSERT INTO sales_order_lines(company_id,order_id,line_no,item_id,ordered_quantity,uom) VALUES($1,$2,1,$3,$4,$5)`,[s.companyId,o.id,p.data.itemId,p.data.quantity,item.base_uom]);
  stage='notification';await notifyStoreManagers(c,{companyId:s.companyId,storeId:context.store_id,eventKey:`request:${o.id}:pending`,title:'Stock request needs approval',message:`${orderNo} was submitted and is waiting for your decision.`,entityType:'sales_order',entityId:o.id});
  stage='audit';await c.query(`INSERT INTO audit_logs(company_id,user_id,action,entity_type,entity_id,details) VALUES($1,$2,'store_request_submitted','sales_order',$3,$4::jsonb)`,[s.companyId,s.userId,o.id,JSON.stringify({storeId:context.store_id,quantity:p.data.quantity,uom:item.base_uom,reference:orderNo})]);return orderNo});
  return Response.redirect(new URL(`/store-portal?created=1&reference=${encodeURIComponent(reference)}`,r.url),303)}catch(e){const known=e instanceof Error&&['STORE_ACCESS','WAREHOUSE','ITEM'].includes(e.message);const databaseCode=typeof e==='object'&&e!==null&&'code'in e?String(e.code):'';console.error('Store stock request failed',{companyId:s.companyId,userId:s.userId,stage,databaseCode,error:e});const code=known?(e as Error).message.toLowerCase().replace('_','-'):databaseCode?`request-save-${stage}-${databaseCode.toLowerCase()}`:'request-save';return Response.redirect(new URL(`/store-portal?error=${code}`,r.url),303)}}
