export default function StoreKnowledge(){return <><div className="page-heading"><div><h1>Store portal guide</h1><p>Quick operating guidance for requesting-store users.</p></div></div><section className="panel">
  <h2>Role guide</h2>
  <ul><li><strong>Store Viewer:</strong> check availability, request and delivery status, transaction history, counts, locators, and personal notifications.</li><li><strong>Store Operator:</strong> request stock, receive deliveries, submit physical counts, returns, transfers, and miscellaneous issues.</li><li><strong>Store Manager:</strong> perform Operator work, maintain locators, and approve or reject store requests, receipts, and transactions.</li></ul>
  <h2>Notifications</h2>
  <ol><li>Select the envelope icon beside <strong>Sign out</strong> to open your inbox.</li><li>Store Managers receive a notification when a stock request, receipt, return, transfer, or miscellaneous issue needs approval.</li><li>The person who submitted the work receives the approval or rejection result, including the manager&apos;s note.</li><li>The red badge is the unread count. Open the inbox to mark one notification—or all notifications—as read.</li><li><strong>Mark read</strong> changes only the inbox indicator; it does not approve the transaction. Select <strong>Open</strong>, review the source record, and use its approval controls.</li></ol>
  <h2>Request stock and approve it</h2>
  <ol><li>On Home, go to <strong>Request stock</strong>, select an item and enter its quantity.</li><li>Select <strong>Add another item</strong> for each additional request line. Duplicate items are not allowed; change the quantity on the existing line instead.</li><li>Enter one required date for the complete request, then submit. A request can contain up to 50 item lines.</li><li>Warevanta generates one reference such as <code>SRQ-STORE-YYYYMM-000001</code>, uses each item&apos;s base unit automatically, and routes the complete request to the store&apos;s default fulfilling warehouse.</li><li>The request remains <strong>Pending Store Approval</strong> and is not released to warehouse allocation.</li><li>A different Store Manager opens Home and scrolls to <strong>Fulfillment → Stock request history</strong>.</li><li>In the pending row&apos;s <strong>Actions</strong> column, select <strong>Approve</strong> or <strong>Reject</strong>. The decision applies to the full request, and a requester cannot approve their own request.</li><li>After Store approval, the assigned warehouse reviews it in <strong>Outbound → Store requests</strong>. Warehouse acceptance releases it to Order management; warehouse rejection notifies the requester with the reason.</li><li>After release, the warehouse continues allocation, picking, packing, and dispatch.</li></ol>
  <h2>Daily sequence</h2>
  <ol><li>Check stock request and approval status on Home and in <strong>Stock request history</strong>.</li><li>Receive only deliveries shown as dispatched.</li><li>Classify the full shipment as accepted, short, or damaged.</li><li>Wait for Store Manager or warehouse management approval before stock becomes available.</li><li>Use Counts for physical verification and Locators for store location references.</li><li>Submit returns, transfers, and miscellaneous issues with an auditable reason; Warevanta generates their references automatically.</li></ol>
  <h2>Mobile scanning and store locator labels</h2>
  <ol><li>Open <strong>Locators</strong> and create a unique code for each receiving area, backroom rack, sales-floor zone, hold area, and damaged-stock area.</li><li>Select <strong>Print label</strong> for one locator or <strong>Print all locator labels</strong> for the active store.</li><li>Choose QR for phone scanning or Code 128 for common handheld scanners, update the preview, and print at 100% scale.</li><li>Attach each label only to its matching physical location and test the scan before operations begin.</li><li>On supported Store Portal scan fields, select <strong>Scan with camera</strong>, allow camera access, and center the item or locator barcode in the frame.</li><li>For receiving, scan the delivery label, an active receiving or backroom locator, and the registered barcode or exact SKU for every delivery line.</li><li>For a return, store transfer, or miscellaneous issue, scan the active source locator and the selected item&apos;s registered barcode or exact SKU before submitting.</li><li>Scans are checked by the server and saved with the transaction for audit; never substitute a receiving, shipment, or document label for the item barcode.</li></ol>
  <div className="knowledge-note"><strong>Request routing:</strong> an Owner, Administrator, or authorized Manager configures the store&apos;s default fulfilling warehouse in <strong>Master data → Requesting stores</strong>. If that warehouse is inactive or unavailable, a new stock request is blocked until the route is corrected.</div>
  <div className="knowledge-note"><strong>Browser sessions during QA:</strong> tabs in the same browser profile share one Warevanta login. Signing in as another user replaces the session in every tab. Use separate browser profiles, an Incognito window, another browser, or another device when testing Operator and Manager accounts simultaneously, and verify the displayed role before acting.</div>
  <div className="knowledge-note"><strong>Scope:</strong> every screen is limited to the requesting store assigned to your account. Store roles do not grant warehouse access.</div>
</section></>}
