import type { Client } from "pg";
import type { Session } from "./auth";
import { withTenant } from "./db";

async function balance(client:Client,companyId:string,itemId:string,locationId:string,lotNumber?:string,expiryDate?:string){const result=await client.query(`SELECT coalesce(sum(quantity),0)::numeric AS quantity FROM inventory_ledger WHERE company_id=$1 AND item_id=$2 AND location_id=$3 AND lot_number IS NOT DISTINCT FROM $4 AND expiry_date IS NOT DISTINCT FROM $5::date`,[companyId,itemId,locationId,lotNumber||null,expiryDate||null]);return Number(result.rows[0].quantity)}

export async function postTransfer(session:Session,input:{itemId:string;fromLocationId:string;toLocationId:string;quantity:number;uom:string;referenceId:string;lotNumber?:string;expiryDate?:string;note?:string}){return withTenant(session.companyId,async client=>{const resources=await client.query(`SELECT i.base_uom,(SELECT warehouse_id FROM locations WHERE company_id=$1 AND id=$3) AS from_warehouse,(SELECT warehouse_id FROM locations WHERE company_id=$1 AND id=$4) AS to_warehouse FROM items i WHERE i.company_id=$1 AND i.id=$2 AND i.status='active'`,[session.companyId,input.itemId,input.fromLocationId,input.toLocationId]);const row=resources.rows[0];if(!row||!row.from_warehouse||!row.to_warehouse)throw new Error('INVALID_SCOPE');if(row.base_uom!==input.uom)throw new Error('UOM_MISMATCH');if(await balance(client,session.companyId,input.itemId,input.fromLocationId,input.lotNumber,input.expiryDate)<input.quantity)throw new Error('INSUFFICIENT_STOCK');const group=crypto.randomUUID();await client.query(`INSERT INTO inventory_ledger(company_id,warehouse_id,location_id,item_id,movement_type,quantity,uom,lot_number,expiry_date,reference_type,reference_id,created_by,transaction_group_id,note) VALUES($1,$2,$3,$4,'transfer_out',$5,$6,$7,$8,'transfer',$9,$10,$11,$12),($1,$13,$14,$4,'transfer_in',$15,$6,$7,$8,'transfer',$9,$10,$11,$12)`,[session.companyId,row.from_warehouse,input.fromLocationId,input.itemId,-input.quantity,input.uom,input.lotNumber||null,input.expiryDate||null,input.referenceId,session.userId,group,input.note||null,row.to_warehouse,input.toLocationId,input.quantity]);return group})}

export async function postAdjustment(session:Session,input:{itemId:string;locationId:string;quantity:number;uom:string;reasonCode:string;referenceId:string;lotNumber?:string;expiryDate?:string;note?:string}){return withTenant(session.companyId,async client=>{const resource=await client.query(`SELECT i.base_uom,l.warehouse_id FROM items i CROSS JOIN locations l WHERE i.company_id=$1 AND l.company_id=$1 AND i.id=$2 AND l.id=$3 AND i.status='active'`,[session.companyId,input.itemId,input.locationId]);const row=resource.rows[0];if(!row)throw new Error('INVALID_SCOPE');if(row.base_uom!==input.uom)throw new Error('UOM_MISMATCH');const reason=await client.query(`SELECT 1 FROM adjustment_reasons WHERE company_id=$1 AND code=$2 AND active=true`,[session.companyId,input.reasonCode]);if(!reason.rowCount)throw new Error('INVALID_REASON');if(input.quantity<0&&await balance(client,session.companyId,input.itemId,input.locationId,input.lotNumber,input.expiryDate)<Math.abs(input.quantity))throw new Error('INSUFFICIENT_STOCK');const group=crypto.randomUUID();await client.query(`INSERT INTO inventory_ledger(company_id,warehouse_id,location_id,item_id,movement_type,quantity,uom,lot_number,expiry_date,reference_type,reference_id,created_by,transaction_group_id,reason_code,note) VALUES($1,$2,$3,$4,'adjustment',$5,$6,$7,$8,'adjustment',$9,$10,$11,$12,$13)`,[session.companyId,row.warehouse_id,input.locationId,input.itemId,input.quantity,input.uom,input.lotNumber||null,input.expiryDate||null,input.referenceId,session.userId,group,input.reasonCode,input.note||null]);return group})}
