CREATE TABLE suppliers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,code text NOT NULL,name text NOT NULL,email text,phone text,status text NOT NULL DEFAULT 'active' CHECK(status IN('active','blocked')),created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(company_id,code),UNIQUE(company_id,id));
CREATE TABLE purchase_orders (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,warehouse_id uuid NOT NULL,supplier_id uuid NOT NULL,po_no text NOT NULL,expected_date date,status text NOT NULL DEFAULT 'draft' CHECK(status IN('draft','open','partial','received','cancelled')),created_by uuid REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(company_id,po_no),UNIQUE(company_id,id),FOREIGN KEY(company_id,warehouse_id) REFERENCES warehouses(company_id,id),FOREIGN KEY(company_id,supplier_id) REFERENCES suppliers(company_id,id));
CREATE TABLE purchase_order_lines (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,purchase_order_id uuid NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,item_id uuid NOT NULL,line_no integer NOT NULL,ordered_quantity numeric(18,6) NOT NULL CHECK(ordered_quantity>0),received_quantity numeric(18,6) NOT NULL DEFAULT 0,uom text NOT NULL,status text NOT NULL DEFAULT 'draft' CHECK(status IN('draft','open','partial','received','cancelled')),UNIQUE(purchase_order_id,line_no),UNIQUE(company_id,id),FOREIGN KEY(company_id,item_id) REFERENCES items(company_id,id));
ALTER TABLE inbound_receipt_lines ADD COLUMN purchase_order_line_id uuid;
ALTER TABLE inbound_receipt_lines ADD CONSTRAINT inbound_receipt_lines_po_line_fk FOREIGN KEY(company_id,purchase_order_line_id) REFERENCES purchase_order_lines(company_id,id);
ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY;ALTER TABLE suppliers FORCE ROW LEVEL SECURITY;ALTER TABLE purchase_orders ENABLE ROW LEVEL SECURITY;ALTER TABLE purchase_orders FORCE ROW LEVEL SECURITY;ALTER TABLE purchase_order_lines ENABLE ROW LEVEL SECURITY;ALTER TABLE purchase_order_lines FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_suppliers ON suppliers USING(company_id=nullif(current_setting('app.company_id',true),'')::uuid) WITH CHECK(company_id=nullif(current_setting('app.company_id',true),'')::uuid);
CREATE POLICY tenant_purchase_orders ON purchase_orders USING(company_id=nullif(current_setting('app.company_id',true),'')::uuid) WITH CHECK(company_id=nullif(current_setting('app.company_id',true),'')::uuid);
CREATE POLICY tenant_purchase_order_lines ON purchase_order_lines USING(company_id=nullif(current_setting('app.company_id',true),'')::uuid) WITH CHECK(company_id=nullif(current_setting('app.company_id',true),'')::uuid);
GRANT SELECT,INSERT,UPDATE,DELETE ON suppliers,purchase_orders,purchase_order_lines TO stockflow_app;
CREATE FUNCTION sync_purchase_order_receipt() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE po_id uuid;
BEGIN
  IF NEW.purchase_order_line_id IS NULL THEN RETURN NEW; END IF;
  UPDATE purchase_order_lines SET received_quantity=NEW.accepted_quantity+NEW.held_quantity+NEW.damaged_quantity,status=CASE WHEN NEW.accepted_quantity+NEW.held_quantity+NEW.damaged_quantity>=ordered_quantity THEN 'received' WHEN NEW.accepted_quantity+NEW.held_quantity+NEW.damaged_quantity>0 THEN 'partial' ELSE 'open' END WHERE id=NEW.purchase_order_line_id RETURNING purchase_order_id INTO po_id;
  UPDATE purchase_orders p SET status=CASE WHEN NOT EXISTS(SELECT 1 FROM purchase_order_lines l WHERE l.purchase_order_id=po_id AND l.status<>'received') THEN 'received' WHEN EXISTS(SELECT 1 FROM purchase_order_lines l WHERE l.purchase_order_id=po_id AND l.received_quantity>0) THEN 'partial' ELSE 'open' END,updated_at=now() WHERE p.id=po_id;
  RETURN NEW;
END $$;
CREATE TRIGGER inbound_receipt_po_progress AFTER UPDATE OF accepted_quantity,held_quantity,damaged_quantity ON inbound_receipt_lines FOR EACH ROW EXECUTE FUNCTION sync_purchase_order_receipt();
