ALTER TABLE locations ADD COLUMN capacity_quantity numeric(18,6) CHECK(capacity_quantity IS NULL OR capacity_quantity>0);
CREATE TABLE item_location_rules (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,item_id uuid NOT NULL,location_id uuid NOT NULL,preferred_putaway boolean NOT NULL DEFAULT false,min_quantity numeric(18,6) NOT NULL DEFAULT 0,target_quantity numeric(18,6) NOT NULL DEFAULT 0,max_quantity numeric(18,6),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(company_id,item_id,location_id),FOREIGN KEY(company_id,item_id) REFERENCES items(company_id,id),FOREIGN KEY(company_id,location_id) REFERENCES locations(company_id,id),CHECK(target_quantity>=min_quantity),CHECK(max_quantity IS NULL OR max_quantity>=target_quantity));
CREATE TABLE replenishment_tasks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,item_id uuid NOT NULL,from_location_id uuid NOT NULL,to_location_id uuid NOT NULL,quantity numeric(18,6) NOT NULL CHECK(quantity>0),uom text NOT NULL,lot_number text,expiry_date date,status text NOT NULL DEFAULT 'pending' CHECK(status IN('pending','completed','cancelled')),created_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz,completed_by uuid REFERENCES users(id),FOREIGN KEY(company_id,item_id) REFERENCES items(company_id,id),FOREIGN KEY(company_id,from_location_id) REFERENCES locations(company_id,id),FOREIGN KEY(company_id,to_location_id) REFERENCES locations(company_id,id));
ALTER TABLE item_location_rules ENABLE ROW LEVEL SECURITY;ALTER TABLE item_location_rules FORCE ROW LEVEL SECURITY;ALTER TABLE replenishment_tasks ENABLE ROW LEVEL SECURITY;ALTER TABLE replenishment_tasks FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_item_location_rules ON item_location_rules USING(company_id=nullif(current_setting('app.company_id',true),'')::uuid) WITH CHECK(company_id=nullif(current_setting('app.company_id',true),'')::uuid);
CREATE POLICY tenant_replenishment_tasks ON replenishment_tasks USING(company_id=nullif(current_setting('app.company_id',true),'')::uuid) WITH CHECK(company_id=nullif(current_setting('app.company_id',true),'')::uuid);
GRANT SELECT,INSERT,UPDATE,DELETE ON item_location_rules,replenishment_tasks TO stockflow_app;
CREATE FUNCTION enforce_location_capacity() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE cap numeric;current_qty numeric;BEGIN IF NEW.quantity<=0 THEN RETURN NEW;END IF;SELECT capacity_quantity INTO cap FROM locations WHERE id=NEW.location_id;IF cap IS NULL THEN RETURN NEW;END IF;SELECT COALESCE(sum(quantity),0) INTO current_qty FROM inventory_ledger WHERE company_id=NEW.company_id AND location_id=NEW.location_id;IF current_qty+NEW.quantity>cap THEN RAISE EXCEPTION 'location_capacity_exceeded';END IF;RETURN NEW;END $$;
CREATE TRIGGER inventory_location_capacity BEFORE INSERT ON inventory_ledger FOR EACH ROW EXECUTE FUNCTION enforce_location_capacity();
