CREATE TABLE approval_rules(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,name text NOT NULL,operation_type text NOT NULL CHECK(operation_type IN('inventory_adjustment','count_variance','order_cancel','order_reopen','dispatch_reversal','return_reversal','forecast_replenishment','purchase_order_release')),threshold_quantity numeric(18,6),required_steps integer NOT NULL DEFAULT 1 CHECK(required_steps BETWEEN 1 AND 5),escalation_hours integer NOT NULL DEFAULT 24 CHECK(escalation_hours BETWEEN 1 AND 720),active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),created_by uuid REFERENCES users(id),UNIQUE(company_id,name));
CREATE TABLE approval_rule_steps(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,rule_id uuid NOT NULL REFERENCES approval_rules(id) ON DELETE CASCADE,step_no integer NOT NULL CHECK(step_no BETWEEN 1 AND 5),approver_role text NOT NULL CHECK(approver_role IN('owner','admin','manager')),UNIQUE(rule_id,step_no));
CREATE TABLE approval_requests(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,rule_id uuid NOT NULL REFERENCES approval_rules(id),operation_type text NOT NULL,entity_type text NOT NULL,entity_id text NOT NULL,metric_quantity numeric(18,6),payload jsonb NOT NULL DEFAULT '{}',status text NOT NULL DEFAULT 'pending' CHECK(status IN('pending','approved','rejected','returned','cancelled','executed')),current_step integer NOT NULL DEFAULT 1,requested_at timestamptz NOT NULL DEFAULT now(),requested_by uuid REFERENCES users(id),completed_at timestamptz);
CREATE TABLE approval_decisions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,request_id uuid NOT NULL REFERENCES approval_requests(id) ON DELETE CASCADE,step_no integer NOT NULL,decision text NOT NULL CHECK(decision IN('approved','rejected','returned')),comment text,decided_at timestamptz NOT NULL DEFAULT now(),decided_by uuid REFERENCES users(id));
CREATE TABLE approval_delegations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,delegator_id uuid NOT NULL REFERENCES users(id),delegate_id uuid NOT NULL REFERENCES users(id),starts_at timestamptz NOT NULL,ends_at timestamptz NOT NULL,active boolean NOT NULL DEFAULT true,CHECK(ends_at>starts_at));
CREATE UNIQUE INDEX approval_requests_pending_unique ON approval_requests(company_id,operation_type,entity_id) WHERE status='pending';
CREATE INDEX approval_requests_inbox_idx ON approval_requests(company_id,status,requested_at);
ALTER TABLE approval_rules ENABLE ROW LEVEL SECURITY;ALTER TABLE approval_rules FORCE ROW LEVEL SECURITY;ALTER TABLE approval_rule_steps ENABLE ROW LEVEL SECURITY;ALTER TABLE approval_rule_steps FORCE ROW LEVEL SECURITY;ALTER TABLE approval_requests ENABLE ROW LEVEL SECURITY;ALTER TABLE approval_requests FORCE ROW LEVEL SECURITY;ALTER TABLE approval_decisions ENABLE ROW LEVEL SECURITY;ALTER TABLE approval_decisions FORCE ROW LEVEL SECURITY;ALTER TABLE approval_delegations ENABLE ROW LEVEL SECURITY;ALTER TABLE approval_delegations FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_approval_rules ON approval_rules USING(company_id=nullif(current_setting('app.company_id',true),'')::uuid) WITH CHECK(company_id=nullif(current_setting('app.company_id',true),'')::uuid);CREATE POLICY tenant_approval_rule_steps ON approval_rule_steps USING(company_id=nullif(current_setting('app.company_id',true),'')::uuid) WITH CHECK(company_id=nullif(current_setting('app.company_id',true),'')::uuid);CREATE POLICY tenant_approval_requests ON approval_requests USING(company_id=nullif(current_setting('app.company_id',true),'')::uuid) WITH CHECK(company_id=nullif(current_setting('app.company_id',true),'')::uuid);CREATE POLICY tenant_approval_decisions ON approval_decisions USING(company_id=nullif(current_setting('app.company_id',true),'')::uuid) WITH CHECK(company_id=nullif(current_setting('app.company_id',true),'')::uuid);CREATE POLICY tenant_approval_delegations ON approval_delegations USING(company_id=nullif(current_setting('app.company_id',true),'')::uuid) WITH CHECK(company_id=nullif(current_setting('app.company_id',true),'')::uuid);GRANT SELECT,INSERT,UPDATE,DELETE ON approval_rules,approval_rule_steps,approval_requests,approval_decisions,approval_delegations TO stockflow_app;
