CREATE TABLE item_uom_conversions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,item_id uuid NOT NULL,uom text NOT NULL,units_per_base numeric(18,6) NOT NULL CHECK(units_per_base>0),active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(company_id,item_id,uom),FOREIGN KEY(company_id,item_id) REFERENCES items(company_id,id) ON DELETE CASCADE);
CREATE TABLE inventory_status_overrides (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,warehouse_id uuid NOT NULL,location_id uuid NOT NULL,item_id uuid NOT NULL,lot_number text,expiry_date date,status text NOT NULL CHECK(status IN('available','hold','quarantine','damaged')),reason text NOT NULL,active boolean NOT NULL DEFAULT true,changed_by uuid REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(company_id,warehouse_id) REFERENCES warehouses(company_id,id),FOREIGN KEY(company_id,location_id) REFERENCES locations(company_id,id),FOREIGN KEY(company_id,item_id) REFERENCES items(company_id,id));
CREATE INDEX inventory_status_lookup_idx ON inventory_status_overrides(company_id,item_id,location_id,created_at DESC) WHERE active;
CREATE VIEW inventory_availability WITH (security_invoker=true) AS
SELECT b.company_id,b.warehouse_id,b.location_id,b.item_id,b.lot_number,b.expiry_date,b.quantity,b.quantity AS on_hand,
CASE WHEN coalesce(o.status,CASE WHEN b.expiry_date<current_date THEN 'expired' WHEN l.type='hold' THEN 'hold' WHEN l.type='damaged' THEN 'damaged' ELSE 'available' END)='available' THEN coalesce((SELECT sum(a.quantity) FROM stock_allocations a JOIN sales_order_lines ol ON ol.id=a.order_line_id WHERE a.company_id=b.company_id AND ol.item_id=b.item_id AND a.location_id=b.location_id AND a.lot_number IS NOT DISTINCT FROM b.lot_number AND a.expiry_date IS NOT DISTINCT FROM b.expiry_date AND a.status='allocated'),0) ELSE 0 END AS reserved,
CASE WHEN coalesce(o.status,CASE WHEN b.expiry_date<current_date THEN 'expired' WHEN l.type='hold' THEN 'hold' WHEN l.type='damaged' THEN 'damaged' ELSE 'available' END)='available' THEN greatest(b.quantity-coalesce((SELECT sum(a.quantity) FROM stock_allocations a JOIN sales_order_lines ol ON ol.id=a.order_line_id WHERE a.company_id=b.company_id AND ol.item_id=b.item_id AND a.location_id=b.location_id AND a.lot_number IS NOT DISTINCT FROM b.lot_number AND a.expiry_date IS NOT DISTINCT FROM b.expiry_date AND a.status='allocated'),0),0) ELSE 0 END AS available_to_promise,
coalesce(o.status,CASE WHEN b.expiry_date<current_date THEN 'expired' WHEN l.type='hold' THEN 'hold' WHEN l.type='damaged' THEN 'damaged' ELSE 'available' END) AS stock_status,o.reason AS status_reason
FROM inventory_balances b JOIN locations l ON l.company_id=b.company_id AND l.id=b.location_id LEFT JOIN LATERAL (SELECT x.status,x.reason FROM inventory_status_overrides x WHERE x.company_id=b.company_id AND x.warehouse_id=b.warehouse_id AND x.location_id=b.location_id AND x.item_id=b.item_id AND x.lot_number IS NOT DISTINCT FROM b.lot_number AND x.expiry_date IS NOT DISTINCT FROM b.expiry_date AND x.active ORDER BY x.created_at DESC LIMIT 1) o ON true;
ALTER TABLE item_uom_conversions ENABLE ROW LEVEL SECURITY; ALTER TABLE item_uom_conversions FORCE ROW LEVEL SECURITY;
ALTER TABLE inventory_status_overrides ENABLE ROW LEVEL SECURITY; ALTER TABLE inventory_status_overrides FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_item_uom_conversions ON item_uom_conversions USING(company_id=nullif(current_setting('app.company_id',true),'')::uuid) WITH CHECK(company_id=nullif(current_setting('app.company_id',true),'')::uuid);
CREATE POLICY tenant_inventory_status_overrides ON inventory_status_overrides USING(company_id=nullif(current_setting('app.company_id',true),'')::uuid) WITH CHECK(company_id=nullif(current_setting('app.company_id',true),'')::uuid);
GRANT SELECT,INSERT,UPDATE,DELETE ON item_uom_conversions,inventory_status_overrides TO stockflow_app;
GRANT SELECT ON inventory_availability TO stockflow_app;
CREATE FUNCTION enforce_allocatable_stock() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN IF NOT EXISTS(SELECT 1 FROM inventory_availability a JOIN sales_order_lines ol ON ol.company_id=a.company_id AND ol.item_id=a.item_id WHERE a.company_id=NEW.company_id AND ol.id=NEW.order_line_id AND a.location_id=NEW.location_id AND a.lot_number IS NOT DISTINCT FROM NEW.lot_number AND a.expiry_date IS NOT DISTINCT FROM NEW.expiry_date AND a.stock_status='available' AND a.available_to_promise>=NEW.quantity) THEN RAISE EXCEPTION 'stock_not_available'; END IF; RETURN NEW; END $$;
CREATE TRIGGER stock_allocation_availability BEFORE INSERT ON stock_allocations FOR EACH ROW EXECUTE FUNCTION enforce_allocatable_stock();
