CREATE TABLE vkit_backorder_substitution_intents(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
 order_id uuid NOT NULL REFERENCES sales_orders(id) ON DELETE CASCADE,component_item_id uuid NOT NULL,relationship_id uuid NOT NULL REFERENCES item_relationships(id) ON DELETE RESTRICT,
 required_component_quantity numeric(18,6) NOT NULL CHECK(required_component_quantity>0),substitute_quantity numeric(18,6) NOT NULL CHECK(substitute_quantity>0),
 status text NOT NULL CHECK(status IN('pending','approved','rejected','applied','cancelled')),approval_request_id uuid REFERENCES approval_requests(id),requested_by uuid NOT NULL REFERENCES users(id),
 created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(company_id,order_id,component_item_id),
 FOREIGN KEY(company_id,component_item_id) REFERENCES items(company_id,id)
);
CREATE INDEX vkit_backorder_substitution_intents_order_idx ON vkit_backorder_substitution_intents(company_id,order_id,status);
ALTER TABLE vkit_backorder_substitution_intents ENABLE ROW LEVEL SECURITY;ALTER TABLE vkit_backorder_substitution_intents FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_vkit_backorder_substitution_intents ON vkit_backorder_substitution_intents USING(company_id=nullif(current_setting('app.company_id',true),'')::uuid) WITH CHECK(company_id=nullif(current_setting('app.company_id',true),'')::uuid);
GRANT SELECT,INSERT,UPDATE,DELETE ON vkit_backorder_substitution_intents TO stockflow_app;

CREATE OR REPLACE FUNCTION notify_vkit_backorder_substitution() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE o sales_orders%ROWTYPE; component_sku text; substitute_sku text;
BEGIN
 IF TG_OP='UPDATE' AND OLD.status IS NOT DISTINCT FROM NEW.status THEN RETURN NEW; END IF;
 SELECT * INTO o FROM sales_orders WHERE company_id=NEW.company_id AND id=NEW.order_id;
 SELECT s.sku,t.sku INTO component_sku,substitute_sku FROM item_relationships r JOIN items s ON s.company_id=r.company_id AND s.id=r.source_item_id JOIN items t ON t.company_id=r.company_id AND t.id=r.target_item_id WHERE r.company_id=NEW.company_id AND r.id=NEW.relationship_id;
 IF NEW.status='approved' AND NOT EXISTS(SELECT 1 FROM vkit_backorder_shortages b LEFT JOIN vkit_backorder_substitution_intents v ON v.company_id=b.company_id AND v.order_id=b.order_id AND v.component_item_id=b.component_item_id LEFT JOIN item_relationships r ON r.company_id=v.company_id AND r.id=v.relationship_id LEFT JOIN LATERAL(SELECT sum(a.available_to_promise) available FROM inventory_availability a WHERE a.company_id=b.company_id AND a.warehouse_id=b.warehouse_id AND a.item_id=r.target_item_id AND a.stock_status='available')stock ON true WHERE b.company_id=NEW.company_id AND b.order_id=NEW.order_id AND b.shortage_quantity>0 AND (v.id IS NULL OR v.status<>'approved' OR coalesce(stock.available,0)<v.substitute_quantity)) THEN UPDATE sales_orders SET backorder_status='ready' WHERE company_id=NEW.company_id AND id=NEW.order_id AND status='new'; END IF;
 INSERT INTO warehouse_notifications(company_id,warehouse_id,user_id,event_key,title,message,order_id)
 SELECT NEW.company_id,o.warehouse_id,m.user_id,'backorder-substitute:'||NEW.id||':'||NEW.status,'VKIT substitute '||NEW.status,o.order_no||': '||component_sku||' → '||substitute_sku||' ('||NEW.substitute_quantity||').',o.id FROM company_members m WHERE m.company_id=NEW.company_id AND m.role IN('owner','admin','manager') AND (m.role='owner' OR EXISTS(SELECT 1 FROM user_warehouse_assignments a WHERE a.company_id=NEW.company_id AND a.user_id=m.user_id AND a.warehouse_id=o.warehouse_id)) ON CONFLICT DO NOTHING;
 IF o.store_id IS NOT NULL THEN INSERT INTO store_notifications(company_id,user_id,store_id,event_key,notification_type,title,message,entity_type,entity_id) SELECT NEW.company_id,u.user_id,o.store_id,'backorder-substitute:'||NEW.id||':'||NEW.status,CASE NEW.status WHEN 'rejected' THEN 'rejected' WHEN 'pending' THEN 'approval_requested' ELSE 'approved' END,'VKIT substitute '||NEW.status,o.order_no||': '||component_sku||' → '||substitute_sku||'.','sales_order',o.id FROM (SELECT o.created_by user_id UNION SELECT a.user_id FROM store_user_assignments a WHERE a.company_id=NEW.company_id AND a.store_id=o.store_id AND a.store_role='store_manager')u ON CONFLICT DO NOTHING; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER vkit_backorder_substitution_notify AFTER INSERT OR UPDATE OF status ON vkit_backorder_substitution_intents FOR EACH ROW EXECUTE FUNCTION notify_vkit_backorder_substitution();

CREATE OR REPLACE VIEW vkit_backorder_shortages WITH (security_invoker=true) AS
SELECT o.company_id,o.id order_id,o.order_no,o.warehouse_id,o.store_id,o.requested_ship_date,o.backorder_status,l.item_id kit_item_id,kit.sku kit_sku,c.component_item_id,component.sku component_sku,(l.ordered_quantity*c.quantity)::numeric(18,6) required_quantity,coalesce(stock.available,0)::numeric(18,6) available_quantity,greatest(l.ordered_quantity*c.quantity-coalesce(stock.available,0),0)::numeric(18,6) shortage_quantity,substitute.relationship_id substitute_relationship_id,substitute.sku substitute_sku,substitute.available_quantity substitute_available_quantity,substitute.conversion_ratio,substitute.approval_required,(o.requested_ship_date<current_date AND o.backorder_status IN('waiting','ready')) overdue
FROM sales_orders o JOIN sales_order_lines l ON l.company_id=o.company_id AND l.order_id=o.id JOIN items kit ON kit.company_id=l.company_id AND kit.id=l.item_id AND kit.item_type='virtual_kit' JOIN item_kit_components c ON c.company_id=l.company_id AND c.kit_item_id=l.item_id AND c.active AND NOT c.optional JOIN items component ON component.company_id=c.company_id AND component.id=c.component_item_id
LEFT JOIN LATERAL(SELECT sum(a.available_to_promise) available FROM inventory_availability a WHERE a.company_id=o.company_id AND a.warehouse_id=o.warehouse_id AND a.item_id=c.component_item_id AND a.stock_status='available')stock ON true
LEFT JOIN LATERAL(SELECT r.id relationship_id,target.sku,sum(a.available_to_promise)::numeric(18,6) available_quantity,r.conversion_ratio,r.approval_required FROM item_relationships r JOIN items target ON target.company_id=r.company_id AND target.id=r.target_item_id AND target.status='active' LEFT JOIN inventory_availability a ON a.company_id=r.company_id AND a.warehouse_id=o.warehouse_id AND a.item_id=r.target_item_id AND a.stock_status='available' WHERE r.company_id=o.company_id AND r.source_item_id=c.component_item_id AND r.relationship_type IN('substitute','reciprocal_substitute','superseded_by') AND r.active AND (r.effective_from IS NULL OR r.effective_from<=current_date) AND (r.effective_to IS NULL OR r.effective_to>=current_date) GROUP BY r.id,target.sku ORDER BY r.priority LIMIT 1)substitute ON true
WHERE o.parent_order_id IS NOT NULL AND o.status='new' AND o.backorder_status IN('waiting','ready');
GRANT SELECT ON vkit_backorder_shortages TO stockflow_app;
