CREATE TABLE carrier_integrations(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,carrier_service_id uuid NOT NULL,mode text NOT NULL DEFAULT 'manual' CHECK(mode IN('manual','api','webhook','hybrid')),api_base_url text,api_key_encrypted text,webhook_secret_encrypted text,
 booking_path text NOT NULL DEFAULT '/shipments',tracking_path_template text NOT NULL DEFAULT '/shipments/{external_id}',active boolean NOT NULL DEFAULT true,last_success_at timestamptz,last_failure_at timestamptz,last_error text,created_at timestamptz NOT NULL DEFAULT now(),created_by uuid REFERENCES users(id),updated_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(company_id,carrier_service_id),FOREIGN KEY(company_id,carrier_service_id) REFERENCES carrier_services(company_id,id)
);
CREATE TABLE carrier_status_mappings(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,carrier_integration_id uuid NOT NULL REFERENCES carrier_integrations(id) ON DELETE CASCADE,external_status text NOT NULL,warevanta_status text NOT NULL CHECK(warevanta_status IN('ready_for_pickup','picked_up','in_transit','out_for_delivery','delivered','failed','returned')),UNIQUE(carrier_integration_id,external_status));
CREATE TABLE carrier_integration_jobs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,carrier_integration_id uuid NOT NULL REFERENCES carrier_integrations(id) ON DELETE CASCADE,shipment_id uuid NOT NULL REFERENCES shipments(id) ON DELETE CASCADE,job_type text NOT NULL CHECK(job_type IN('book','poll','label')),status text NOT NULL DEFAULT 'pending' CHECK(status IN('pending','processing','completed','retry','dead_letter')),attempts integer NOT NULL DEFAULT 0,next_attempt_at timestamptz NOT NULL DEFAULT now(),request_payload jsonb,response_payload jsonb,last_error text,completed_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(carrier_integration_id,shipment_id,job_type));
CREATE TABLE carrier_webhook_events(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,carrier_integration_id uuid NOT NULL REFERENCES carrier_integrations(id) ON DELETE CASCADE,provider_event_id text NOT NULL,payload_hash text NOT NULL,status text NOT NULL DEFAULT 'received' CHECK(status IN('received','processed','ignored','failed')),error_message text,received_at timestamptz NOT NULL DEFAULT now(),processed_at timestamptz,UNIQUE(carrier_integration_id,provider_event_id));
ALTER TABLE shipments ADD COLUMN external_shipment_id text,ADD COLUMN external_label_url text,ADD COLUMN carrier_last_sync_at timestamptz,ADD COLUMN carrier_sync_status text NOT NULL DEFAULT 'manual' CHECK(carrier_sync_status IN('manual','pending','synced','failed'));
CREATE FUNCTION enqueue_carrier_booking() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN INSERT INTO carrier_integration_jobs(company_id,carrier_integration_id,shipment_id,job_type,request_payload) SELECT NEW.company_id,i.id,NEW.id,'book',jsonb_build_object('shipmentNo',NEW.shipment_no,'trackingNumber',NEW.tracking_number) FROM carrier_integrations i WHERE i.company_id=NEW.company_id AND i.carrier_service_id=NEW.carrier_service_id AND i.active AND i.mode IN('api','hybrid') ON CONFLICT DO NOTHING;IF FOUND THEN UPDATE shipments SET carrier_sync_status='pending' WHERE id=NEW.id;END IF;RETURN NEW;END $$;
CREATE TRIGGER shipment_carrier_booking AFTER INSERT ON shipments FOR EACH ROW EXECUTE FUNCTION enqueue_carrier_booking();
CREATE FUNCTION carrier_webhook_config(p_id uuid) RETURNS TABLE(id uuid,company_id uuid,carrier_service_id uuid,webhook_secret_encrypted text) LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$SELECT i.id,i.company_id,i.carrier_service_id,i.webhook_secret_encrypted FROM carrier_integrations i WHERE i.id=p_id AND i.active AND i.mode IN('webhook','hybrid')$$;REVOKE ALL ON FUNCTION carrier_webhook_config(uuid) FROM PUBLIC;GRANT EXECUTE ON FUNCTION carrier_webhook_config(uuid) TO stockflow_app;
ALTER TABLE carrier_integrations ENABLE ROW LEVEL SECURITY;ALTER TABLE carrier_integrations FORCE ROW LEVEL SECURITY;ALTER TABLE carrier_status_mappings ENABLE ROW LEVEL SECURITY;ALTER TABLE carrier_status_mappings FORCE ROW LEVEL SECURITY;ALTER TABLE carrier_integration_jobs ENABLE ROW LEVEL SECURITY;ALTER TABLE carrier_integration_jobs FORCE ROW LEVEL SECURITY;ALTER TABLE carrier_webhook_events ENABLE ROW LEVEL SECURITY;ALTER TABLE carrier_webhook_events FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_carrier_integrations ON carrier_integrations USING(company_id=nullif(current_setting('app.company_id',true),'')::uuid) WITH CHECK(company_id=nullif(current_setting('app.company_id',true),'')::uuid);CREATE POLICY tenant_carrier_status_mappings ON carrier_status_mappings USING(company_id=nullif(current_setting('app.company_id',true),'')::uuid) WITH CHECK(company_id=nullif(current_setting('app.company_id',true),'')::uuid);CREATE POLICY tenant_carrier_integration_jobs ON carrier_integration_jobs USING(company_id=nullif(current_setting('app.company_id',true),'')::uuid) WITH CHECK(company_id=nullif(current_setting('app.company_id',true),'')::uuid);CREATE POLICY tenant_carrier_webhook_events ON carrier_webhook_events USING(company_id=nullif(current_setting('app.company_id',true),'')::uuid) WITH CHECK(company_id=nullif(current_setting('app.company_id',true),'')::uuid);
GRANT SELECT,INSERT,UPDATE,DELETE ON carrier_integrations,carrier_status_mappings,carrier_integration_jobs,carrier_webhook_events TO stockflow_app;
CREATE INDEX carrier_integration_jobs_queue_idx ON carrier_integration_jobs(status,next_attempt_at);CREATE INDEX carrier_webhook_events_received_idx ON carrier_webhook_events(company_id,received_at DESC);
