CREATE TABLE carrier_contracts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,carrier_service_id uuid NOT NULL,contract_number text NOT NULL,title text NOT NULL,status text NOT NULL DEFAULT 'active' CHECK(status IN('draft','active','expired','terminated')),effective_from date NOT NULL,effective_to date NOT NULL,renewal_notice_days integer NOT NULL DEFAULT 60 CHECK(renewal_notice_days BETWEEN 1 AND 365),contract_reference text,notes text,created_by uuid NOT NULL REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(company_id,contract_number),FOREIGN KEY(company_id,carrier_service_id) REFERENCES carrier_services(company_id,id),CHECK(effective_to>=effective_from));
CREATE TABLE carrier_sla_automation_configs(company_id uuid PRIMARY KEY REFERENCES companies(id) ON DELETE CASCADE,enabled boolean NOT NULL DEFAULT true,review_day integer NOT NULL DEFAULT 3 CHECK(review_day BETWEEN 1 AND 28),contract_warning_days integer NOT NULL DEFAULT 60 CHECK(contract_warning_days BETWEEN 1 AND 365),corrective_action_grace_hours integer NOT NULL DEFAULT 24 CHECK(corrective_action_grace_hours BETWEEN 0 AND 720),updated_by uuid REFERENCES users(id),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE carrier_sla_notifications(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),company_id uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,carrier_service_id uuid REFERENCES carrier_services(id) ON DELETE CASCADE,warehouse_id uuid REFERENCES warehouses(id) ON DELETE CASCADE,event_key text NOT NULL,title text NOT NULL,message text NOT NULL,link_path text NOT NULL DEFAULT '/app/carrier-scorecards/governance',read_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(company_id,user_id,event_key));
ALTER TABLE carrier_performance_reviews ADD COLUMN generation_source text NOT NULL DEFAULT 'manual' CHECK(generation_source IN('manual','scheduled')),ADD COLUMN breach_count integer NOT NULL DEFAULT 0 CHECK(breach_count>=0);
CREATE INDEX carrier_contract_expiry_idx ON carrier_contracts(company_id,status,effective_to);CREATE INDEX carrier_sla_notification_inbox_idx ON carrier_sla_notifications(company_id,user_id,read_at,created_at DESC);
ALTER TABLE carrier_contracts ENABLE ROW LEVEL SECURITY;ALTER TABLE carrier_contracts FORCE ROW LEVEL SECURITY;ALTER TABLE carrier_sla_automation_configs ENABLE ROW LEVEL SECURITY;ALTER TABLE carrier_sla_automation_configs FORCE ROW LEVEL SECURITY;ALTER TABLE carrier_sla_notifications ENABLE ROW LEVEL SECURITY;ALTER TABLE carrier_sla_notifications FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_carrier_contracts ON carrier_contracts USING(company_id=nullif(current_setting('app.company_id',true),'')::uuid) WITH CHECK(company_id=nullif(current_setting('app.company_id',true),'')::uuid);CREATE POLICY tenant_carrier_sla_automation_configs ON carrier_sla_automation_configs USING(company_id=nullif(current_setting('app.company_id',true),'')::uuid) WITH CHECK(company_id=nullif(current_setting('app.company_id',true),'')::uuid);CREATE POLICY tenant_carrier_sla_notifications ON carrier_sla_notifications USING(company_id=nullif(current_setting('app.company_id',true),'')::uuid) WITH CHECK(company_id=nullif(current_setting('app.company_id',true),'')::uuid);
GRANT SELECT,INSERT,UPDATE,DELETE ON carrier_contracts,carrier_sla_automation_configs,carrier_sla_notifications TO stockflow_app;
INSERT INTO carrier_sla_automation_configs(company_id,updated_by) SELECT c.id,m.user_id FROM companies c JOIN LATERAL(SELECT user_id FROM company_members WHERE company_id=c.id AND role='owner' ORDER BY user_id LIMIT 1)m ON true ON CONFLICT DO NOTHING;
