import Link from "next/link";
import { getSession } from "../../../../lib/auth";
import { tenantRows } from "../../../../lib/db";
export const metadata={title:'Adjust stock'};export const dynamic='force-dynamic';
type Item={id:string;sku:string;description:string;base_uom:string};type Location={id:string;code:string;warehouse:string};type Reason={code:string;description:string};
const messages:Record<string,string>={insufficient_stock:'This adjustment would create negative stock.',uom_mismatch:'Use the item base unit for this adjustment.',invalid_reason:'Select an active adjustment reason.',invalid_scope:'The selected item or location is not available.',invalid:'Check all required adjustment fields.'};
export default async function Adjust({searchParams}:{searchParams:Promise<{error?:string}>}){
  const session=await getSession();const {error}=await searchParams;
  const items=session?await tenantRows<Item>(session.companyId,`SELECT id,sku,description,base_uom FROM items WHERE company_id=$1 AND status='active' ORDER BY sku`,[session.companyId]):[];
  const locations=session?await tenantRows<Location>(session.companyId,`SELECT l.id,l.code,w.name AS warehouse FROM locations l JOIN warehouses w ON w.company_id=l.company_id AND w.id=l.warehouse_id WHERE l.company_id=$1 AND l.active=true ORDER BY w.name,l.code`,[session.companyId]):[];
  const reasons=session?await tenantRows<Reason>(session.companyId,`SELECT code,description FROM adjustment_reasons WHERE company_id=$1 AND active=true ORDER BY description`,[session.companyId]):[];
  return <div className="app-content"><div className="page-heading"><div><h1>Adjust stock</h1><p>Post a controlled correction without editing inventory history.</p></div><Link href="/app/inventory" className="button button-secondary">Cancel</Link></div>{error&&<div className="form-error">{messages[error]||'The adjustment could not be posted.'}</div>}<div className="form-layout"><form className="panel form-section" method="post" action="/api/inventory/adjust"><h2>Adjustment details</h2><div className="field"><label htmlFor="itemId">Item</label><select id="itemId" name="itemId" required>{items.map(item=><option key={item.id} value={item.id}>{item.sku} — {item.description} ({item.base_uom})</option>)}</select></div><div className="field"><label htmlFor="locationId">Location</label><select id="locationId" name="locationId" required>{locations.map(location=><option key={location.id} value={location.id}>{location.warehouse} · {location.code}</option>)}</select></div><div className="form-row"><div className="field"><label htmlFor="quantity">Quantity change</label><input id="quantity" name="quantity" type="number" step="any" placeholder="Use - for a reduction" required/></div><div className="field"><label htmlFor="uom">Base unit</label><input id="uom" name="uom" placeholder="EA" required/></div></div><div className="form-row"><div className="field"><label htmlFor="lotNumber">Lot number</label><input id="lotNumber" name="lotNumber"/></div><div className="field"><label htmlFor="expiryDate">Expiry date</label><input id="expiryDate" name="expiryDate" type="date"/></div></div><div className="form-row"><div className="field"><label htmlFor="reasonCode">Reason</label><select id="reasonCode" name="reasonCode" required>{reasons.map(reason=><option key={reason.code} value={reason.code}>{reason.description}</option>)}</select></div><div className="field"><label htmlFor="referenceId">Reference</label><input id="referenceId" name="referenceId" placeholder="ADJ-0001" required/></div></div><div className="field"><label htmlFor="note">Explanation</label><textarea id="note" name="note" rows={3} required/></div><button className="button button-primary" type="submit">Post adjustment</button></form><aside className="panel"><h2>Adjustment controls</h2><ul className="help-list"><li>Only owners, administrators, and managers may adjust stock.</li><li>Every adjustment requires a reason and reference.</li><li>Reductions cannot create negative stock.</li><li>Existing movements remain unchanged.</li></ul></aside></div></div>
}
