import assert from "node:assert/strict";
import pg from "pg";

const appUrl=process.env.APP_URL||"http://localhost:3000";
const admin=new pg.Client({connectionString:process.env.DATABASE_ADMIN_URL});
const appDb=new pg.Client({connectionString:process.env.DATABASE_URL});
await admin.connect();await appDb.connect();
const stamp=`${Date.now()}-${Math.floor(Math.random()*10000)}`;
const createdUsers=[];const createdCompanies=[];

async function post(path,data,cookie){const response=await fetch(`${appUrl}${path}`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded',...(cookie?{cookie}:{})},body:new URLSearchParams(data),redirect:'manual'});if(![302,303,307,308].includes(response.status))throw new Error(`${path} returned ${response.status}: ${await response.text()}`);return {location:response.headers.get('location'),cookie:response.headers.get('set-cookie')?.split(';')[0]}}

try{
  const email1=`owner-${stamp}@tenant-a.test`;const signup1=await post('/api/auth/signup',{company:'Tenant A Smoke Test',email:email1,password:'SmokeTest!2026-A'});assert.equal(signup1.location,`${appUrl}/app/dashboard`);assert.ok(signup1.cookie);
  const account1=(await admin.query(`SELECT u.id AS user_id,m.company_id,w.id AS warehouse_id FROM users u JOIN company_members m ON m.user_id=u.id JOIN warehouses w ON w.company_id=m.company_id WHERE u.email=$1`,[email1])).rows[0];assert.ok(account1);createdUsers.push(account1.user_id);createdCompanies.push(account1.company_id);
  await post('/api/locations',{warehouseId:account1.warehouse_id,code:'REC-01',type:'receiving'},signup1.cookie);
  await post('/api/locations',{warehouseId:account1.warehouse_id,code:'STOR-01',type:'storage'},signup1.cookie);
  await post('/api/locations',{warehouseId:account1.warehouse_id,code:'PACK-01',type:'packing'},signup1.cookie);
  await post('/api/locations',{warehouseId:account1.warehouse_id,code:'HOLD-01',type:'hold'},signup1.cookie);
  await post('/api/locations',{warehouseId:account1.warehouse_id,code:'DMG-01',type:'damaged'},signup1.cookie);
  await post('/api/items',{sku:'SMOKE-001',name:'Smoke Test Item',category:'Testing',status:'active',uom:'EA',barcodeMode:'auto',barcode:'',format:'code128',tracking:'lot_expiry',allocation:'fefo'},signup1.cookie);
  const item=(await admin.query(`SELECT id FROM items WHERE company_id=$1 AND sku='SMOKE-001'`,[account1.company_id])).rows[0];const locations=(await admin.query(`SELECT code,id FROM locations WHERE company_id=$1`,[account1.company_id])).rows;const source=locations.find(row=>row.code==='REC-01');const destination=locations.find(row=>row.code==='STOR-01');assert.ok(item&&source&&destination);
  await post('/api/inventory/receive',{warehouseId:account1.warehouse_id,locationId:source.id,itemId:item.id,quantity:'48',uom:'EA',referenceId:'PO-SMOKE-001',lotNumber:'LOT-SMOKE',expiryDate:'2027-12-31'},signup1.cookie);
  const transfer=await post('/api/inventory/transfer',{itemId:item.id,fromLocationId:source.id,toLocationId:destination.id,quantity:'10',uom:'EA',referenceId:'TR-SMOKE-001',lotNumber:'LOT-SMOKE',expiryDate:'2027-12-31',note:'Putaway'},signup1.cookie);assert.equal(transfer.location,`${appUrl}/app/inventory?transferred=1`);
  const adjustment=await post('/api/inventory/adjust',{itemId:item.id,locationId:source.id,quantity:'-3',uom:'EA',reasonCode:'DAMAGE',referenceId:'ADJ-SMOKE-001',lotNumber:'LOT-SMOKE',expiryDate:'2027-12-31',note:'Three units damaged'},signup1.cookie);assert.equal(adjustment.location,`${appUrl}/app/inventory?adjusted=1`);
  const rejected=await post('/api/inventory/adjust',{itemId:item.id,locationId:source.id,quantity:'-999',uom:'EA',reasonCode:'LOSS',referenceId:'ADJ-SMOKE-NEG',lotNumber:'LOT-SMOKE',expiryDate:'2027-12-31',note:'Must be rejected'},signup1.cookie);assert.match(rejected.location,/error=insufficient_stock/);
  await appDb.query('BEGIN');await appDb.query("SELECT set_config('app.company_id',$1,true)",[account1.company_id]);const balances=(await appDb.query(`SELECT location_id,quantity::text FROM inventory_balances WHERE company_id=$1 AND item_id=$2`,[account1.company_id,item.id])).rows;await appDb.query('COMMIT');assert.equal(Number(balances.find(row=>row.location_id===source.id).quantity),35);assert.equal(Number(balances.find(row=>row.location_id===destination.id).quantity),10);
  const hold=locations.find(row=>row.code==='HOLD-01');const damaged=locations.find(row=>row.code==='DMG-01');const createdReceipt=await post('/api/receiving',{warehouseId:account1.warehouse_id,receiptNo:'GR-SMOKE-001',supplier:'Smoke Supplier',externalReference:'PO-SMOKE-002',expectedDate:'2026-08-06',itemId:item.id,expectedQuantity:'7',uom:'EA'},signup1.cookie);const receiptId=createdReceipt.location.split('/').pop();const inbound=(await admin.query(`SELECT rl.id AS line_id FROM inbound_receipts r JOIN inbound_receipt_lines rl ON rl.receipt_id=r.id WHERE r.id=$1`,[receiptId])).rows[0];const inspected=await post(`/api/receiving/${receiptId}/inspect`,{lineId:inbound.line_id,receivingLocationId:source.id,putawayLocationId:destination.id,holdLocationId:hold.id,damagedLocationId:damaged.id,acceptedQuantity:'5',heldQuantity:'1',damagedQuantity:'1',lotNumber:'LOT-INBOUND',expiryDate:'2028-01-31'},signup1.cookie);assert.match(inspected.location,/inspected=1/);const task=(await admin.query(`SELECT id FROM putaway_tasks WHERE receipt_line_id=$1`,[inbound.line_id])).rows[0];const completed=await post(`/api/putaway/${task.id}/complete`,{},signup1.cookie);assert.match(completed.location,/putaway=1/);const receiptState=(await admin.query(`SELECT status FROM inbound_receipts WHERE id=$1`,[receiptId])).rows[0];assert.equal(receiptState.status,'completed');

  const createdOrder=await post('/api/orders',{warehouseId:account1.warehouse_id,orderNo:'SO-SMOKE-001',customer:'Smoke Customer',requestedShipDate:'2026-08-07',priority:'normal',itemId:item.id,quantity:'12',uom:'EA'},signup1.cookie);const orderId=createdOrder.location.split('/').pop();assert.ok(orderId);
  const allocated=await post(`/api/orders/${orderId}/allocate`,{},signup1.cookie);assert.match(allocated.location,/allocated=1/);const picks=(await admin.query(`SELECT p.id,p.quantity::text,l.code FROM pick_tasks p JOIN stock_allocations a ON a.id=p.allocation_id JOIN sales_order_lines ol ON ol.id=a.order_line_id JOIN locations l ON l.id=p.from_location_id WHERE ol.order_id=$1 ORDER BY p.expiry_date`,[orderId])).rows;assert.equal(picks.length,2);assert.deepEqual(picks.map(p=>Number(p.quantity)),[10,2]);const barcode=(await admin.query(`SELECT barcode_value FROM item_barcodes WHERE company_id=$1 AND item_id=$2 AND is_primary=true`,[account1.company_id,item.id])).rows[0];assert.ok(barcode);for(const pick of picks){const picked=await post(`/api/picks/${pick.id}/complete`,{locationCode:pick.code,barcode:barcode.barcode_value},signup1.cookie);assert.match(picked.location,/picked=1/)}const dispatch=await post(`/api/orders/${orderId}/dispatch`,{},signup1.cookie);assert.match(dispatch.location,/dispatched=1/);const outboundState=(await admin.query(`SELECT status FROM sales_orders WHERE id=$1`,[orderId])).rows[0];assert.equal(outboundState.status,'dispatched');const shipment=await admin.query(`SELECT 1 FROM shipments WHERE order_id=$1`,[orderId]);assert.equal(shipment.rowCount,1);

  const createdCount=await post('/api/counts',{warehouseId:account1.warehouse_id,countNo:'CC-SMOKE-001',countType:'cycle',locationId:destination.id,blindCount:'on'},signup1.cookie);const countId=createdCount.location.split('/').pop();assert.ok(countId);const countLine=(await admin.query(`SELECT id,system_quantity::text FROM inventory_count_lines WHERE count_id=$1`,[countId])).rows[0];assert.equal(Number(countLine.system_quantity),3);const counted=await post(`/api/counts/lines/${countLine.id}/submit`,{locationCode:'STOR-01',barcode:barcode.barcode_value,countedQuantity:'2'},signup1.cookie);assert.match(counted.location,/saved=1/);const approved=await post(`/api/counts/${countId}/approve`,{},signup1.cookie);assert.match(approved.location,/approved=1/);const countState=(await admin.query(`SELECT status FROM inventory_counts WHERE id=$1`,[countId])).rows[0];assert.equal(countState.status,'approved');const varianceMovement=(await admin.query(`SELECT quantity::text FROM inventory_ledger WHERE reference_type='inventory_count' AND reference_id=$1`,[countId])).rows[0];assert.equal(Number(varianceMovement.quantity),-1);
  const reportPage=await fetch(`${appUrl}/app/reports?type=variances`,{headers:{cookie:signup1.cookie}});assert.equal(reportPage.status,200);assert.match(await reportPage.text(),/CC-SMOKE-001/);const csvReport=await fetch(`${appUrl}/api/reports/export?type=fulfillment`,{headers:{cookie:signup1.cookie}});assert.equal(csvReport.status,200);assert.match(csvReport.headers.get('content-type'),/text\/csv/);assert.match(await csvReport.text(),/SO-SMOKE-001/);
  const keyResponse=await fetch(`${appUrl}/api/integrations`,{method:'POST',headers:{cookie:signup1.cookie,'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({name:'Smoke ERP',accessLevel:'write'})});assert.equal(keyResponse.status,200);const keyHtml=await keyResponse.text();const apiKey=keyHtml.match(/sf_live_[a-f0-9]{8}_[a-f0-9]{48}/)?.[0];assert.ok(apiKey);const apiHeaders={authorization:`Bearer ${apiKey}`};const apiItems=await fetch(`${appUrl}/api/v1/items?sku=SMOKE-001`,{headers:apiHeaders});assert.equal(apiItems.status,200);assert.equal((await apiItems.json()).count,1);const apiStock=await fetch(`${appUrl}/api/v1/inventory?sku=SMOKE-001&location=STOR-01`,{headers:apiHeaders});assert.equal(apiStock.status,200);assert.equal(Number((await apiStock.json()).data[0].quantity),2);const adjustmentBody=JSON.stringify({sku:'SMOKE-001',location:'STOR-01',quantity:1,reference:'ERP-SMOKE-001',lotNumber:'LOT-INBOUND',expiryDate:'2028-01-31'});const writeHeaders={...apiHeaders,'content-type':'application/json','idempotency-key':'erp-smoke-001'};const apiAdjustment=await fetch(`${appUrl}/api/v1/inventory/adjustments`,{method:'POST',headers:writeHeaders,body:adjustmentBody});assert.equal(apiAdjustment.status,201);const apiReplay=await fetch(`${appUrl}/api/v1/inventory/adjustments`,{method:'POST',headers:writeHeaders,body:adjustmentBody});assert.equal(apiReplay.status,201);const erpMoves=await admin.query(`SELECT count(*)::int AS n FROM inventory_ledger WHERE company_id=$1 AND reference_type='erp' AND reference_id='ERP-SMOKE-001'`,[account1.company_id]);assert.equal(erpMoves.rows[0].n,1);
  const invitedEmail=`operator-${stamp}@tenant-a.test`;const inviteResponse=await fetch(`${appUrl}/api/users`,{method:'POST',headers:{cookie:signup1.cookie,'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({name:'Smoke Operator',email:invitedEmail,role:'operator'})});assert.equal(inviteResponse.status,200);const temporaryPassword=(await inviteResponse.text()).match(/Sf![a-f0-9]{18}aA1/)?.[0];assert.ok(temporaryPassword);const invited=(await admin.query(`SELECT id FROM users WHERE email=$1`,[invitedEmail])).rows[0];createdUsers.push(invited.id);const firstSignin=await post('/api/auth/signin',{email:invitedEmail,password:temporaryPassword});assert.equal(firstSignin.location,`${appUrl}/account/password`);assert.ok(firstSignin.cookie);const changed=await post('/api/account/password',{currentPassword:temporaryPassword,newPassword:'Permanent!Smoke2026',confirmPassword:'Permanent!Smoke2026'},firstSignin.cookie);assert.match(changed.location,/signin\?changed=1/);const finalSignin=await post('/api/auth/signin',{email:invitedEmail,password:'Permanent!Smoke2026'});assert.equal(finalSignin.location,`${appUrl}/app/dashboard`);const auditEvents=await admin.query(`SELECT count(*)::int AS n FROM audit_logs WHERE company_id=$1 AND action IN('user_invited','password_changed')`,[account1.company_id]);assert.equal(auditEvents.rows[0].n,2);

  const email2=`owner-${stamp}@tenant-b.test`;const signup2=await post('/api/auth/signup',{company:'Tenant B Smoke Test',email:email2,password:'SmokeTest!2026-B'});const account2=(await admin.query(`SELECT u.id AS user_id,m.company_id FROM users u JOIN company_members m ON m.user_id=u.id WHERE u.email=$1`,[email2])).rows[0];assert.ok(account2);createdUsers.push(account2.user_id);createdCompanies.push(account2.company_id);
  await appDb.query('BEGIN');await appDb.query("SELECT set_config('app.company_id',$1,true)",[account2.company_id]);const leaked=await appDb.query(`SELECT 1 FROM items WHERE id=$1`,[item.id]);await appDb.query('COMMIT');assert.equal(leaked.rowCount,0);
  console.log('Verified warehouse workflows, reporting, ERP APIs, secure user invitations, forced password change, audit history, and cross-company isolation.');
}finally{
  await appDb.query('ROLLBACK').catch(()=>undefined);
  if(createdCompanies.length)await admin.query('DELETE FROM companies WHERE id = ANY($1::uuid[])',[createdCompanies]);
  if(createdUsers.length)await admin.query('DELETE FROM users WHERE id = ANY($1::uuid[])',[createdUsers]);
  await appDb.end();await admin.end();
}
