const operations=[['Inventory adjustment','Absolute adjustment quantity'],['Count variance','Sum of absolute count-line variances'],['Order cancellation / reopening','Total ordered quantity'],['Dispatch reversal','Quantity issued by the shipment'],['Return reversal','Return-line quantity'],['Forecast replenishment','Recommended replenishment quantity'],['Purchase order release','Total PO quantity']];
const decisions=[['Approve','Records approval for the current step. If another step remains, the request advances; final approval executes the original operation.'],['Return','Closes the request as Returned. A correction comment is required; the underlying operation is not executed.'],['Reject','Closes the request as Rejected. A rejection comment is required; the underlying operation is not executed.']];

export default function ModuleTwelve(){return <section className="panel" id="module-12">
  <div className="panel-heading"><div><p className="eyebrow">Module 12</p><h2>Approvals, Exceptions, and Notifications</h2><p>Goal: route higher-risk actions to accountable decision-makers, keep warehouse problems visible, and preserve the reason for every decision.</p></div><span className="badge">Current lesson</span></div>
  <h3>Approval and exception are different</h3>
  <table className="data-table"><thead><tr><th>Control</th><th>Purpose</th></tr></thead><tbody><tr><td><strong>Approval</strong></td><td>Pauses a requested high-risk transaction until the required role accepts, returns, or rejects it.</td></tr><tr><td><strong>Exception</strong></td><td>Records an operational problem such as a short pick or order hold that requires investigation and resolution.</td></tr><tr><td><strong>Notification</strong></td><td>Alerts a user that an approval requires attention or that their request reached an outcome.</td></tr></tbody></table>
  <h3>How an approval is triggered</h3>
  <pre className="knowledge-tree">User requests controlled action → Warevanta finds an active matching rule{`\n`}→ Metric meets threshold → Approval request is created{`\n`}→ Required decision step(s) → Final approval executes action</pre>
  <p>If there is no active matching rule, or the absolute metric is below the rule threshold, the operation executes through its normal route without an approval request. When several rules match the same operation, Warevanta selects the applicable rule with the highest threshold.</p>
  <div className="knowledge-note"><strong>Threshold means “at or above”:</strong> a threshold of 25 applies when the absolute metric is 25 or more. Leaving it blank makes the rule apply at every quantity.</div>
  <h3>Available approval metrics</h3>
  <table className="data-table"><thead><tr><th>Operation</th><th>Quantity compared with threshold</th></tr></thead><tbody>{operations.map(x=><tr key={x[0]}><td><strong>{x[0]}</strong></td><td>{x[1]}</td></tr>)}</tbody></table>
  <h3>Create a safe training rule</h3>
  <p>As an Owner or Administrator, open <strong>Control center → Approvals</strong> and create:</p>
  <table className="data-table"><tbody><tr><th>Name</th><td>Training large count variance</td></tr><tr><th>Operation</th><td>Count variance</td></tr><tr><th>Threshold</th><td>10 EA</td></tr><tr><th>Steps</th><td>1 approval step</td></tr><tr><th>Step 1 role</th><td>Manager</td></tr><tr><th>Escalation</th><td>24 hours</td></tr></tbody></table>
  <p>Only Owners and Administrators can create, edit, enable, or disable rules. The current screen supports one or two sequential approval steps. Disable a rule when it should stop governing new requests; existing requests retain their workflow record.</p>
  <h3>Multi-step decisions</h3>
  <p>Step 1 must approve before Step 2 becomes active. Warevanta notifies company members holding the role assigned to the current step. A user can act only when their current company role matches that step or a valid delegation gives them that authority.</p>
  <table className="data-table"><thead><tr><th>Decision</th><th>Result</th></tr></thead><tbody>{decisions.map(x=><tr key={x[0]}><td><strong>{x[0]}</strong></td><td>{x[1]}</td></tr>)}</tbody></table>
  <div className="knowledge-note"><strong>Final approval is transactional:</strong> Warevanta executes the original adjustment, reversal, order control, PO release, count posting, or forecast conversion only after the last required approval succeeds.</div>
  <h3>Review an approval properly</h3>
  <ol><li>Confirm the operation type and originating record.</li><li>Review the displayed metric against the rule threshold.</li><li>Open the related operational page and verify quantities, state, reason, and evidence.</li><li>Check that the requested action is still valid and needed.</li><li>Add a clear comment, especially when returning or rejecting.</li><li>Select the correct decision once; do not use approval as a substitute for investigation.</li></ol>
  <h3>Delegating approval authority</h3>
  <p>An Owner, Administrator, or Manager can use <strong>Delegate my approvals</strong> to select another company user and a start and end time. During that active period, the delegate may decide steps that require the delegator’s role. The delegation is audited and can be revoked by the delegator, Owner, or Administrator.</p>
  <ul><li>Use delegation for planned absence, not routine password sharing.</li><li>Select a competent user and the shortest practical time window.</li><li>Communicate which requests may arrive and what evidence is required.</li><li>Revoke early when coverage is no longer needed.</li><li>Remember that delegation transfers decision authority; it does not change the delegate’s normal company role.</li></ul>
  <h3>Notifications and overdue indicators</h3>
  <p>Unread in-app notifications appear at the top of Approvals. New requests notify the current step’s role. Moving to the next step clears older request notifications and alerts the next role. Return, rejection, and final execution notify the requester.</p>
  <p><strong>Mark all read</strong> only clears the unread indicator; it does not approve, reject, or close any request. A pending request is labeled Overdue when its original request time plus the rule’s escalation hours is earlier than the current time.</p>
  <div className="knowledge-note"><strong>Current escalation boundary:</strong> overdue is a visual indicator. The current local system does not automatically email, reassign, approve, or escalate the request to another role. Users must monitor the Approvals page.</div>
  <h3>How a short-pick exception begins</h3>
  <p>During mobile picking, an Operator, Manager, Administrator, or Owner can report <strong>Cannot complete this pick</strong> with Not found, Damaged, Wrong stock, Location blocked, or Other, plus a useful note. Warevanta then:</p>
  <ol><li>Marks the pick task Exception.</li><li>Releases its stock allocation.</li><li>Reduces the order line’s allocated quantity.</li><li>Places the order on Hold while remembering its previous status.</li><li>Adds the problem to <strong>Control center → Fulfillment exceptions</strong>.</li></ol>
  <h3>Resolve a short pick</h3>
  <p>An Owner, Administrator, or Manager chooses one of two outcomes:</p>
  <table className="data-table"><thead><tr><th>Resolution</th><th>Behavior</th></tr></thead><tbody><tr><td><strong>Reallocate from another location</strong></td><td>Searches another Storage or Picking balance with enough available quantity, creates a new allocation and pick task, and returns the order to Allocated.</td></tr><tr><td><strong>Cancel this pick task</strong></td><td>Cancels the failed task and restores the order’s prior status, or Picking when no prior state is available. The unmet quantity is not automatically fulfilled.</td></tr></tbody></table>
  <p>Reallocation currently requires one alternate location/lot with enough available stock for the full exception quantity. If none exists, Warevanta reports that no alternate location has sufficient stock.</p>
  <h3>Controlled order actions</h3>
  <p>The Fulfillment exceptions page also provides manager-level order controls:</p>
  <table className="data-table"><thead><tr><th>Action</th><th>Effect</th></tr></thead><tbody><tr><td><strong>Hold</strong></td><td>Pauses an eligible order and records its prior status and reason.</td></tr><tr><td><strong>Resume</strong></td><td>Restores a held order to its recorded prior state and resolves open order-hold exceptions.</td></tr><tr><td><strong>Cancel</strong></td><td>Releases eligible allocations and cancels pending/exception tasks. It cannot cancel dispatched or materially progressed orders.</td></tr><tr><td><strong>Reopen</strong></td><td>Returns a Cancelled order to New.</td></tr></tbody></table>
  <p>Cancellation and reopening may require approval based on configured quantity thresholds. Hold and Resume execute directly when the order state permits. Reasons include Customer request, Address check, Payment hold, Stock exception, and Other.</p>
  <h3>Audit expectations</h3>
  <p>Use notes that another person can understand later: what was observed, which item/location/order was affected, what evidence was checked, what action is recommended, and why. Approval requests, decisions, delegations, exception reports, resolutions, and final executions create audit records.</p>
  <h3>Current functional boundaries</h3>
  <ul><li>Approval notifications are currently in-app; local email delivery is not part of this workflow.</li><li>Overdue status does not initiate automatic escalation or reminders.</li><li>Returning a request closes it; there is no in-screen edit-and-resubmit chain tied to the same request.</li><li>Delegation applies broadly to steps matching the delegator’s role, not to one selected operation type.</li><li>The inbox shows the entity identifier but does not yet provide a direct related-record link for every operation.</li><li>Short-pick reallocation cannot split the replacement across several alternate balances.</li></ul>
  <h3>Common mistakes</h3>
  <ul><li>Leaving a threshold blank when only large transactions should require approval.</li><li>Assigning a step role that no active company member holds.</li><li>Using the same person for request and approval without considering separation of duties.</li><li>Approving from the inbox without reviewing the related transaction.</li><li>Writing “wrong” or “reject” instead of a useful correction comment.</li><li>Marking a notification read and assuming the request was processed.</li><li>Creating long, unnecessary delegations or delegating to an untrained user.</li><li>Reporting a false completed pick instead of opening an exception.</li><li>Cancelling a failed pick without planning how the remaining order quantity will be fulfilled.</li></ul>
  <h3>Practice checklist</h3>
  <ul className="knowledge-checklist"><li>Create a one-step training approval rule with a safe threshold</li><li>Trigger a request using a controlled training transaction</li><li>Confirm the operation has not executed while Pending</li><li>Sign in as the assigned role and review the source record</li><li>Approve and confirm the operation executes only after final approval</li><li>Practice Return or Reject on a separate safe request with a clear comment</li><li>Create and revoke a short test delegation</li><li>Mark a notification read and confirm request status is unchanged</li><li>Report a training short-pick exception</li><li>Resolve it by reallocation when alternate stock exists</li><li>Review the audit history for request, decision, and resolution</li></ul>
  <div className="knowledge-checkpoint"><strong>Module 12 checkpoint</strong><p>Explain what triggers an approval, the difference between Return and Reject in the current system, and what Warevanta does to an order when a short pick is reported.</p></div>
</section>}
