const endpoints=[['GET','/api/v1/items','Read','Lists Item Master data and barcodes; optional exact SKU filter.'],['GET','/api/v1/inventory','Read','Returns on hand, reserved, ATP, status, lot, and expiry; optional exact SKU, warehouse, and location filters.'],['POST','/api/v1/inventory/adjustments','Write','Posts a positive or negative ERP inventory adjustment. Requires Idempotency-Key.'],['POST','/api/v1/purchase-orders','Write','Creates a Draft PO using existing supplier, warehouse, and item codes. Requires Idempotency-Key.']];
const statuses=[['200','Successful read or replayed response whose original status was 200'],['201','Write transaction created, or a successful write response safely replayed'],['400','Missing idempotency key, invalid JSON/payload, invalid master data, insufficient stock, or another business validation failure'],['401','Missing, malformed, revoked, unknown, or read-only credential used for a write']];

export default function ModuleFourteen(){return <section className="panel" id="module-14">
  <div className="panel-heading"><div><p className="eyebrow">Module 14</p><h2>ERP APIs and Integrations</h2><p>Goal: exchange item, inventory, adjustment, and purchasing data without sharing user passwords or crossing company boundaries.</p></div><span className="badge">Current lesson</span></div>
  <h3>What an API integration does</h3>
  <p>An application programming interface, or API, lets an authorized ERP, accounting, ecommerce, or automation system request structured data or submit a supported transaction. Each credential belongs to one Warevanta company and every successful authenticated query is restricted to that company.</p>
  <pre className="knowledge-tree">External system → HTTPS + API key → Warevanta validation{`\n`}→ Company-isolated data or controlled transaction → JSON response</pre>
  <div className="knowledge-note"><strong>API is not screen automation:</strong> the external system sends documented fields directly. It must still follow Item Master codes, UOM conversions, location codes, tracking details, authorization, and business controls.</div>
  <h3>Create the correct credential</h3>
  <p>As an Owner or Administrator, open <strong>Administration → ERP integrations</strong>. Enter a descriptive name such as <strong>Training ERP read only</strong> and select:</p>
  <table className="data-table"><thead><tr><th>Access</th><th>Capability</th><th>Recommended use</th></tr></thead><tbody><tr><td><strong>Read only</strong></td><td>Items and inventory GET endpoints</td><td>Reporting, availability lookup, ecommerce display, and initial testing</td></tr><tr><td><strong>Read and post adjustments</strong></td><td>All current read and write endpoints, including Draft PO creation</td><td>Approved transactional integrations that genuinely require writes</td></tr></tbody></table>
  <p>Select <strong>Generate secure key</strong>, copy the complete key immediately, and store it in the external system’s secret manager. Warevanta displays the secret only once; the credentials page later shows only its prefix, access level, last use, and status.</p>
  <div className="knowledge-note"><strong>Least privilege:</strong> begin training with Read only. A Write key can change real inventory and create real Draft purchase orders.</div>
  <h3>Protect API keys</h3>
  <ul><li>Never put a key in browser-side JavaScript, screenshots, chat, source code, Git, spreadsheets, or support tickets.</li><li>Send it only through the HTTPS Authorization header.</li><li>Use separate credentials for each external system and environment.</li><li>Give credentials descriptive names so activity can be attributed.</li><li>Revoke a key immediately if exposed, unused, or no longer owned by a trusted system.</li><li>Warevanta stores a one-way hash for authentication; it cannot reveal the original secret later.</li></ul>
  <h3>Authentication</h3>
  <p>Every API request sends:</p>
  <pre className="knowledge-command">Authorization: Bearer YOUR_API_KEY</pre>
  <p>The key format begins with <code>sf_live_</code> even in the current local environment. Treat that label as sensitive production-style material. Revoking a credential makes subsequent requests unauthorized.</p>
  <h3>Supported endpoints</h3>
  <table className="data-table"><thead><tr><th>Method</th><th>Endpoint</th><th>Minimum access</th><th>Purpose</th></tr></thead><tbody>{endpoints.map(x=><tr key={x[1]}><td><strong>{x[0]}</strong></td><td><code>{x[1]}</code></td><td>{x[2]}</td><td>{x[3]}</td></tr>)}</tbody></table>
  <h3>Read Item Master data</h3>
  <pre className="knowledge-command">GET https://localhost/api/v1/items?sku=TRAIN-COLA-330</pre>
  <p>The response contains SKU, description, category, base UOM, tracking method, allocation method, status, and registered barcodes with value, format, UOM, and primary flag. Omitting <code>sku</code> lists up to 500 items ordered by SKU.</p>
  <p>The SKU comparison is exact. Use the code stored in Warevanta rather than a description or an external alias.</p>
  <h3>Read inventory availability</h3>
  <pre className="knowledge-command">GET https://localhost/api/v1/inventory?sku=TRAIN-COLA-330&amp;warehouse=MNL&amp;location=A-01-01</pre>
  <p>Each row provides SKU, warehouse, location, lot, expiry, on hand, reserved, available to promise, stock status, and base UOM. Any combination of exact <code>sku</code>, <code>warehouse</code>, and <code>location</code> may be omitted. Results are limited to 1,000 rows.</p>
  <div className="knowledge-note"><strong>Use ATP for promises:</strong> On hand can include quantities that are reserved, held, damaged, quarantined, or expired. External order promises should use Available to promise and Stock status.</div>
  <h3>Idempotency for write transactions</h3>
  <p>Every supported POST endpoint requires a unique header such as:</p>
  <pre className="knowledge-command">Idempotency-Key: erp-adjustment-TRAIN-0001</pre>
  <p>Warevanta stores the result against the API client and key. Repeating the same write with that key returns the original response instead of posting again. This protects against timeouts and network retries.</p>
  <ul><li>Use one stable key for one intended business transaction.</li><li>Never reuse it for a different body or business event.</li><li>If a logged business failure is corrected, submit the corrected transaction with a new key; replaying the old key returns its stored failure.</li><li>Store the idempotency key with the external document or message identifier.</li></ul>
  <h3>Post an inventory adjustment</h3>
  <p>A Write credential can send JSON containing:</p>
  <pre className="knowledge-command">{`{\n  "sku": "TRAIN-COLA-330",\n  "location": "A-01-01",\n  "quantity": 1,\n  "uom": "EA",\n  "reference": "ERP-TRAIN-ADJ-001",\n  "lotNumber": "LOT-TRAIN-001",\n  "expiryDate": "2026-09-21",\n  "reasonCode": "CORRECTION",\n  "note": "Approved training correction"\n}`}</pre>
  <p>The quantity cannot be zero. Positive quantity adds inventory; negative quantity removes it. Warevanta normalizes a configured alternate UOM into the item’s base UOM and blocks a negative adjustment that exceeds the exact location/lot/expiry balance.</p>
  <p>A successful response returns the transaction ID, Posted status, entered quantity/UOM, and normalized base quantity/UOM. The ledger movement is <strong>erp adjustment</strong> with the external reference.</p>
  <div className="knowledge-note"><strong>Tracking responsibility:</strong> for lot- or expiry-managed stock, the external integration must send the correct tracking values. The current endpoint accepts optional lot and expiry fields rather than deriving them from a barcode scan.</div>
  <h3>Create a Draft purchase order</h3>
  <p>A Write credential can submit a header and one or more lines:</p>
  <pre className="knowledge-command">{`{\n  "poNo": "ERP-TRAIN-PO-001",\n  "supplierCode": "TRAIN-SUP",\n  "warehouseCode": "MNL",\n  "expectedDate": "2026-09-01",\n  "lines": [\n    { "sku": "TRAIN-COLA-330", "quantity": 48, "uom": "EA" }\n  ]\n}`}</pre>
  <p>The supplier must be Active, warehouse Active, and every item Active. Codes are matched in the company workspace. A successful request creates a <strong>Draft</strong> PO; it does not release receiving work. An authorized user must review supplier, warehouse, date, lines, quantities, and UOM before release.</p>
  <div className="knowledge-note"><strong>Current PO API boundary:</strong> the endpoint stores the submitted line quantity and UOM. The external system must send a valid operational UOM and quantity; API-side UOM normalization for PO lines is not yet enforced like inventory adjustment normalization.</div>
  <h3>Understand responses</h3>
  <table className="data-table"><thead><tr><th>Status</th><th>Meaning</th></tr></thead><tbody>{statuses.map(x=><tr key={x[0]}><td><strong>{x[0]}</strong></td><td>{x[1]}</td></tr>)}</tbody></table>
  <p>Error bodies contain a short <code>error</code> value such as <code>invalid_payload</code>, <code>not_found</code>, <code>insufficient_stock</code>, or <code>item_not_found:SKU</code>. External systems should log the HTTP status, error value, endpoint, reference, and idempotency key without logging the API secret.</p>
  <h3>Use integration activity</h3>
  <p>The ERP integrations page shows the latest 20 logged authenticated API requests with time, client name, method, path, and status. GET successes and write results are recorded. Credential Last used is updated during successful authentication.</p>
  <p>Use activity to confirm which client called an endpoint and whether it succeeded. The current screen does not display request bodies or full response bodies, and some early failures—such as missing authentication, missing idempotency header, or invalid JSON—may return before an activity row is stored.</p>
  <h3>Safe integration test sequence</h3>
  <ol><li>Create a dedicated Read-only training credential.</li><li>Store it securely and test the exact TRAIN-COLA-330 item lookup.</li><li>Test inventory lookup and reconcile On hand, Reserved, ATP, lot, expiry, and status with the Warevanta screen.</li><li>Confirm the requests appear under Recent API activity.</li><li>Revoke the training key and confirm it receives 401 afterward.</li><li>Only when authorized, create a separate Write training credential.</li><li>Post a controlled +1 adjustment with a unique reference and idempotency key.</li><li>Replay the identical request and confirm inventory changes only once.</li><li>Post an approved −1 correction with a different reference and key to restore the original balance.</li><li>Revoke the Write training credential.</li></ol>
  <h3>Current integration boundaries</h3>
  <ul><li>There is no interactive API documentation, webhook subscription, OAuth, IP allowlist, per-endpoint scope, or key-expiry setting yet.</li><li>Read endpoints use fixed row limits rather than cursor pagination.</li><li>Filters are exact matches and do not provide description search.</li><li>Write access is broad across both supported write endpoints.</li><li>Credential rotation requires creating a new key, updating the external system, testing it, then revoking the old key.</li><li>Inventory adjustments do not pass through the user-facing approval-rule workflow.</li><li>Integration logs shown to users are limited to the latest 20 requests.</li></ul>
  <h3>Common mistakes</h3>
  <ul><li>Giving Write access to a system that only reads stock.</li><li>Losing the one-time key before storing it securely.</li><li>Putting the key in a URL or application source code.</li><li>Using descriptions instead of exact SKU and location codes.</li><li>Promising On hand rather than ATP.</li><li>Retrying a write with a new idempotency key after a timeout and causing a duplicate.</li><li>Reusing one idempotency key for different transactions.</li><li>Sending CASE without a configured conversion for adjustments.</li><li>Omitting lot or expiry from tracked stock corrections.</li><li>Creating a PO through the API and assuming it is already released.</li><li>Leaving unused or compromised credentials active.</li></ul>
  <h3>Practice checklist</h3>
  <ul className="knowledge-checklist"><li>Create a named Read-only training credential</li><li>Copy it once into secure temporary storage</li><li>Read TRAIN-COLA-330 Item Master data</li><li>Read its warehouse/location/lot inventory availability</li><li>Reconcile On hand, Reserved, ATP, and status</li><li>Review the successful requests in integration activity</li><li>Revoke the key and confirm access is denied</li><li>If authorized, test a net-zero pair of idempotent ERP adjustments</li><li>Replay one identical request and confirm no duplicate movement</li><li>Review the ERP reference in Inventory movements</li><li>Remove training secrets from tools and temporary storage</li></ul>
  <div className="knowledge-checkpoint"><strong>Module 14 checkpoint</strong><p>Explain why ATP differs from On hand, why every write needs an idempotency key, and why an API credential must never be placed in browser code or Git.</p></div>
</section>}
