const types=[['Cycle count','One selected location','Frequent verification of a manageable stock area without counting the entire warehouse.'],['Physical count','One selected location','A formally planned physical verification of all system-listed stock in that location.'],['Wall-to-wall count','Entire selected warehouse','A comprehensive count across all eligible locations in the warehouse.']];
const states=[['Open','Count lines are ready for physical observation.'],['Counted','Every line has been entered; variances can be reviewed.'],['Approved','Authorized review is complete and variance adjustments were posted.'],['Cancelled','The count was replaced by a variance recount and cannot be approved.']];

export default function ModuleTen(){return <section className="panel" id="module-10">
  <div className="panel-heading"><div><p className="eyebrow">Module 10</p><h2>Cycle, Physical, and Wall-to-Wall Counts</h2><p>Goal: compare physical stock with Warevanta, investigate differences, and post only reviewed, auditable corrections.</p></div><span className="badge">Current lesson</span></div>
  <h3>Why inventory counts matter</h3>
  <p>A count tests whether the quantity physically present for an exact item, location, lot, and expiry agrees with the inventory ledger. It can identify picking errors, unposted movements, misplaced stock, damage, theft, unit mistakes, and process weaknesses.</p>
  <h3>Choose the correct count type</h3>
  <table className="data-table"><thead><tr><th>Type</th><th>Current Warevanta scope</th><th>Use</th></tr></thead><tbody>{types.map(x=><tr key={x[0]}><td><strong>{x[0]}</strong></td><td>{x[1]}</td><td>{x[2]}</td></tr>)}</tbody></table>
  <div className="knowledge-note"><strong>Current scope rule:</strong> Cycle and Physical counts require one location. Wall-to-wall uses the entire warehouse. Hold and Damaged location types are excluded from generated lines.</div>
  <h3>Blind versus visible counts</h3>
  <p>In a <strong>blind count</strong>, the system quantity stays hidden until the operator submits the physical quantity. This reduces the temptation to copy or “count toward” the expected value. In a <strong>visible count</strong>, the expected quantity is shown while counting. Blind counting is recommended for reliable verification.</p>
  <h3>Plan a safe training count</h3>
  <p>Open <strong>Inventory control → Inventory counts</strong>. Choose a quiet location holding TRAIN-COLA-330 and create:</p>
  <table className="data-table"><tbody><tr><th>Count number</th><td>TRAIN-COUNT-001</td></tr><tr><th>Type</th><td>Cycle count</td></tr><tr><th>Warehouse</th><td>The warehouse containing the training stock</td></tr><tr><th>Location</th><td>The exact Storage or Picking location to count</td></tr><tr><th>Blind count</th><td>Enabled</td></tr></tbody></table>
  <p>The count captures the current system quantity for each eligible inventory balance in scope. A scope with no eligible balances cannot create a count.</p>
  <h3>Control warehouse activity during counting</h3>
  <p>Tell receiving, putaway, transfer, picking, replenishment, and adjustment operators not to move stock through the count location until approval is complete. Mark the physical area as under count and record the start time.</p>
  <div className="knowledge-note"><strong>Important current behavior:</strong> Warevanta takes a snapshot but does not technically freeze transactions. At approval, it verifies that each current balance still equals its starting snapshot. If stock moved, approval is rejected as stale and a fresh count is required.</div>
  <h3>Count each line</h3>
  <ol><li>Go to the location displayed on the count line.</li><li>Scan or enter that exact location code.</li><li>Scan a barcode registered to the displayed item.</li><li>Count the exact item, lot, and expiry shown on the line.</li><li>Enter the physical quantity in the displayed base UOM.</li><li>Enter <strong>0</strong> when the expected stock is physically absent; do not leave it pending.</li><li>Select <strong>Save count</strong> and continue until every line is complete.</li></ol>
  <p>Warevanta validates the location and item barcode. When the last line is saved, the count changes from Open to Counted and reveals expected quantities and variances.</p>
  <h3>Understand the variance</h3>
  <pre className="knowledge-tree">Variance = Counted quantity − System quantity</pre>
  <table className="data-table"><thead><tr><th>Result</th><th>Meaning</th><th>Example</th></tr></thead><tbody><tr><td>Zero</td><td>Physical and system quantities agree.</td><td>Counted 48 − System 48 = 0</td></tr><tr><td>Positive</td><td>More stock was found than Warevanta recorded.</td><td>Counted 50 − System 48 = +2</td></tr><tr><td>Negative</td><td>Less stock was found than Warevanta recorded.</td><td>Counted 46 − System 48 = −2</td></tr></tbody></table>
  <h3>Investigate before adjustment</h3>
  <p>Before approving a variance, check nearby locations, recent receipts, putaway, transfers, picks, dispatches, returns, adjustments, UOM conversions, lot and expiry selection, and unposted physical paperwork. Correct an unfinished operational transaction through its proper workflow when possible.</p>
  <h3>Create a variance recount</h3>
  <p>An Owner, Administrator, or Manager may select <strong>Create variance recount</strong> after all lines are counted. The new count is blind and includes only lines whose absolute variance exceeds the applicable threshold. The original count becomes Cancelled.</p>
  <ul><li>For scheduled counts, the schedule’s recount threshold is used.</li><li>For a manually created count, the effective threshold is zero, so every non-zero variance is recounted.</li><li>If no variance exceeds the threshold, no recount is created.</li><li>The recount must be completed before the original workflow can proceed; approval applies to the active recount.</li></ul>
  <h3>Approve and post variances</h3>
  <p>An Owner, Administrator, or Manager may select <strong>Approve and post variances</strong>. If a Count variance approval rule is configured and its threshold is met, Warevanta sends the request to <strong>Control center → Approvals</strong>. Otherwise it posts immediately.</p>
  <p>For each non-zero variance, Warevanta creates a <strong>count adjustment</strong> at the exact location, item, lot, and expiry using reason <code>COUNT_VARIANCE</code>. Zero-variance lines create no ledger quantity. The count then becomes Approved.</p>
  <div className="knowledge-note"><strong>Counts do not overwrite history:</strong> the approved difference is added as a ledger movement. The pre-count balance, physical observation, approver, and resulting adjustment remain traceable.</div>
  <h3>Automated cycle-count schedules</h3>
  <p>Owners, Administrators, and Managers can create recurring schedules by warehouse or location, ABC class, frequency, first-run time, blind-count setting, and recount threshold. <strong>Generate now</strong> creates the next eligible cycle count immediately.</p>
  <h3>ABC classification</h3>
  <p><strong>Recalculate ABC classes</strong> ranks items using the last 90 days of shipment and picking movement:</p>
  <table className="data-table"><thead><tr><th>Class</th><th>Current calculation</th><th>Typical counting approach</th></tr></thead><tbody><tr><td><strong>A</strong></td><td>Highest-moving items contributing roughly the first 70% of cumulative movement</td><td>Count most frequently</td></tr><tr><td><strong>B</strong></td><td>Next movement band up to roughly 90%</td><td>Count moderately often</td></tr><tr><td><strong>C</strong></td><td>Remaining or no-movement items</td><td>Count less frequently, but still periodically</td></tr></tbody></table>
  <h3>Count statuses</h3>
  <table className="data-table"><thead><tr><th>Status</th><th>Meaning</th></tr></thead><tbody>{states.map(x=><tr key={x[0]}><td><strong>{x[0]}</strong></td><td>{x[1]}</td></tr>)}</tbody></table>
  <h3>Current functional boundaries</h3>
  <ul><li>Generated lines cover balances already known to Warevanta; an unrecorded item found unexpectedly has no ad-hoc count line in the current screen.</li><li>Serial-by-serial count capture is not yet provided by this count page.</li><li>There is no hard transaction freeze; operational coordination is required.</li><li>A stale count must be recreated rather than approved against a changed balance.</li><li>These boundaries should be included in later QA and production-readiness decisions.</li></ul>
  <h3>Common mistakes</h3>
  <ul><li>Counting the correct SKU in the wrong location.</li><li>Combining different lots or expiry dates into one number.</li><li>Counting cases but entering the number as EA.</li><li>Leaving a missing item pending instead of entering zero.</li><li>Moving stock through the location while the count is open.</li><li>Approving before investigating unposted transactions.</li><li>Using an adjustment to hide a process error that should be corrected at its source.</li><li>Allowing the same person to count, recount, and approve without independent review.</li></ul>
  <h3>Practice checklist</h3>
  <ul className="knowledge-checklist"><li>Select a quiet training location with known stock</li><li>Create blind cycle count TRAIN-COUNT-001</li><li>Pause physical movements through the location</li><li>Scan the correct location and item barcode for every line</li><li>Count by exact item, lot, expiry, and base UOM</li><li>Enter zero for any expected stock not physically present</li><li>Review every revealed variance</li><li>Create a recount for a safe intentional training variance</li><li>Complete the blind recount independently</li><li>Approve only after confirming no stock moved since the snapshot</li><li>Review the COUNT_VARIANCE ledger entry and final Approved status</li></ul>
  <div className="knowledge-checkpoint"><strong>Module 10 checkpoint</strong><p>Explain the difference between a blind count and a hard inventory freeze, how variance is calculated, and why Warevanta rejects a stale count at approval.</p></div>
</section>}
