const terms=[['Minimum','The trigger. A task is considered only when current stock in the Picking location is below this quantity.'],['Target','The desired quantity after replenishment. Task quantity is normally Target minus current stock, limited by eligible reserve stock.'],['Maximum','An optional planning value shown with the rule. The current task generator does not yet enforce it separately.'],['Safety stock','Extra forecast coverage intended to protect against demand or lead-time uncertainty.'],['Lead time','Planning days allowed for supplier replenishment. It influences the forecast but does not create a purchase order.'],['Forecast horizon','The future period—1, 7, 14, or 30 days—covered by the recommendation.']];

export default function ModuleEleven(){return <section className="panel" id="module-11">
  <div className="panel-heading"><div><p className="eyebrow">Module 11</p><h2>Replenishment and Forecasting</h2><p>Goal: keep Picking locations supplied from Storage while controlling when suggested work becomes a physical inventory movement.</p></div><span className="badge">Current lesson</span></div>
  <h3>What replenishment means</h3>
  <p>Replenishment moves stock already owned by the company from a reserve <strong>Storage</strong> location to a forward <strong>Picking</strong> location. It does not receive new stock, purchase from a supplier, or change company-total on hand.</p>
  <pre className="knowledge-tree">Storage reserve → Replenishment task → Scan and move → Picking location</pre>
  <div className="knowledge-note"><strong>Operational purpose:</strong> Picking bins should contain enough accessible stock for fulfillment, while reserve stock remains organized in Storage.</div>
  <h3>Planning terms</h3>
  <table className="data-table"><thead><tr><th>Term</th><th>Meaning in Warevanta</th></tr></thead><tbody>{terms.map(x=><tr key={x[0]}><td><strong>{x[0]}</strong></td><td>{x[1]}</td></tr>)}</tbody></table>
  <h3>Method 1: Minimum-and-target replenishment</h3>
  <p>Open <strong>Warehouse operations → Putaway &amp; replenishment</strong>. Create a training item-location rule:</p>
  <table className="data-table"><tbody><tr><th>Item</th><td>TRAIN-COLA-330</td></tr><tr><th>Location</th><td>Your training Picking location</td></tr><tr><th>Minimum</th><td>12 EA</td></tr><tr><th>Target</th><td>36 EA</td></tr><tr><th>Maximum</th><td>48 EA, optional</td></tr><tr><th>Preferred reserve putaway</th><td>Leave off for the Picking location</td></tr></tbody></table>
  <p>Minimum must not exceed Target, and Maximum—when supplied—must not be lower than Target. Only Owners, Administrators, and Managers can configure rules or generate tasks.</p>
  <h3>How task generation works</h3>
  <p>Select <strong>Generate replenishment tasks</strong>. For each Picking rule, Warevanta:</p>
  <ol><li>Calculates the item balance in the destination Picking location.</li><li>Creates no task unless the balance is below Minimum.</li><li>Suppresses a duplicate if a pending task already exists for the same item and destination.</li><li>Searches the same warehouse for a positive Storage balance.</li><li>Selects one source location, lot, and expiry using preferred-reserve and item-allocation ordering.</li><li>Creates a task for the smaller of the amount needed to reach Target and the selected reserve balance.</li></ol>
  <pre className="knowledge-tree">Threshold task = min(Target − Picking balance, selected reserve balance)</pre>
  <p>For FEFO items, the earliest eligible expiry is preferred. FIFO favors the oldest stock; LIFO favors the newest. A generated task is only planned work—inventory has not moved yet.</p>
  <h3>Execute the task</h3>
  <ol><li>Go to the displayed Storage source.</li><li>Confirm the item, quantity, lot, and expiry.</li><li>Scan the exact source-location code.</li><li>Scan a barcode registered to the item.</li><li>Move the physical stock to the displayed Picking destination.</li><li>Scan the exact destination-location code.</li><li>Select <strong>Confirm</strong>.</li></ol>
  <p>Warevanta verifies both locations, the barcode, task state, and available stock for the exact lot and expiry. Completion posts equal <strong>replenish out</strong> and <strong>replenish in</strong> movements and marks the task Completed.</p>
  <table className="data-table"><thead><tr><th>Measure</th><th>Effect at completion</th></tr></thead><tbody><tr><td>Storage balance</td><td>Decreases by the task quantity</td></tr><tr><td>Picking balance</td><td>Increases by the same quantity</td></tr><tr><td>Company on hand</td><td>No change</td></tr></tbody></table>
  <h3>Preferred reserve and capacity</h3>
  <p>A Storage rule can flag a bin as a preferred reserve source. The threshold generator prioritizes it before applying the item’s stock-rotation sequence. Location capacity can also be recorded and reviewed on this page.</p>
  <div className="knowledge-note"><strong>Current boundary:</strong> capacity and Maximum are visible planning controls, but the current generator and completion route do not enforce them as hard limits. Verify destination space physically before moving stock.</div>
  <h3>Method 2: Replenishment forecasting</h3>
  <p>Open <strong>Planning → Replenishment forecasting</strong>. Add a rule for an item and active Picking location. For training, use Safety stock <strong>6 EA</strong>, Lead time <strong>7 days</strong>, and Forecast horizon <strong>14 days</strong>.</p>
  <p>When an Owner, Administrator, or Manager selects <strong>Run forecast</strong>, Warevanta uses:</p>
  <ul><li><strong>Average daily usage:</strong> shipment issues during the last 30 days divided by 30.</li><li><strong>Open demand:</strong> remaining ordered quantity on orders not Cancelled or Dispatched.</li><li><strong>Picking stock:</strong> current balance in the rule’s Picking location.</li><li><strong>Time coverage:</strong> Lead time plus Forecast horizon.</li><li><strong>Safety stock:</strong> the extra quantity in the planning rule.</li></ul>
  <pre className="knowledge-tree">Planned need = max(Open demand, Daily usage × (Lead time + Horizon) + Safety stock)<br/>Recommended = ceil(Planned need − Picking stock)</pre>
  <p>The recommendation is limited by one positive Storage balance in the same warehouse. Its source is selected by earliest expiry first, then higher available quantity. If need is zero or no reserve stock exists, no recommendation is created.</p>
  <h3>Read the forecast</h3>
  <table className="data-table"><thead><tr><th>Field</th><th>Interpretation</th></tr></thead><tbody><tr><td>Recommended quantity</td><td>Suggested reserve-to-pick movement, not an automatic purchase quantity.</td></tr><tr><td>Daily usage</td><td>Historical 30-day shipment rate; new or seasonal items may show little useful history.</td></tr><tr><td>Open demand</td><td>Outstanding sales-order demand for the item.</td></tr><tr><td>Days of cover</td><td>Current Picking stock divided by average daily usage.</td></tr><tr><td>Projected stockout</td><td>Current date plus whole days of cover when historical usage is positive.</td></tr></tbody></table>
  <h3>Approve or reject a recommendation</h3>
  <p>Review demand, promotions, seasonality, delayed orders, supplier constraints, reserve availability, destination space, and unusual shipments. Add a useful manager note, then:</p>
  <ul><li><strong>Approve task:</strong> converts the recommendation into a pending replenishment task, unless a Forecast replenishment approval rule first routes it through Approvals.</li><li><strong>Reject:</strong> closes it without creating warehouse work.</li><li><strong>Run forecast again:</strong> rejects all still-pending recommendations as superseded and creates a fresh set.</li></ul>
  <div className="knowledge-note"><strong>Recommendation is not execution:</strong> even after approval, stock remains unchanged until an operator scans and confirms the resulting task.</div>
  <h3>Threshold versus forecast</h3>
  <table className="data-table"><thead><tr><th>Method</th><th>Trigger</th><th>Best use</th></tr></thead><tbody><tr><td><strong>Minimum and target</strong></td><td>Picking stock is already below a fixed minimum</td><td>Simple, predictable bin replenishment</td></tr><tr><td><strong>Forecast</strong></td><td>Projected need exceeds current Picking stock</td><td>Anticipating demand before the bin reaches its minimum</td></tr></tbody></table>
  <h3>Current forecasting boundaries</h3>
  <ul><li>The calculation is a simple operational forecast, not machine learning.</li><li>Historical usage uses a fixed 30-day shipment window.</li><li>Open demand is item-level and is not currently narrowed to the planning warehouse.</li><li>It does not directly account for incoming POs, supplier reliability, promotions, seasonality, returns, or reserved stock.</li><li>It selects one Storage balance per recommendation; another run may be needed for additional lots.</li><li>Approval creates an internal movement task, not a purchase recommendation or PO.</li></ul>
  <h3>Common mistakes</h3>
  <ul><li>Setting Minimum to zero and expecting a low-stock trigger.</li><li>Setting Target lower than Minimum.</li><li>Creating the destination rule on Storage instead of Picking.</li><li>Assuming a generated or approved task already moved stock.</li><li>Moving a different lot from the displayed task.</li><li>Scanning the source but not verifying the destination.</li><li>Treating forecast quantity as a supplier order quantity.</li><li>Approving without checking physical capacity.</li><li>Running a new forecast without realizing pending recommendations are superseded.</li></ul>
  <h3>Practice checklist</h3>
  <ul className="knowledge-checklist"><li>Confirm TRAIN-COLA-330 exists in Storage and Picking</li><li>Create a Picking rule with Minimum 12 and Target 36 EA</li><li>Review destination capacity</li><li>Generate a task only when Picking is below Minimum</li><li>Confirm no inventory changed at generation</li><li>Scan source, item, and destination to complete it</li><li>Verify balanced replenish-out and replenish-in movements</li><li>Create a forecast rule with safety stock, lead time, and horizon</li><li>Run and interpret the forecast</li><li>Approve or reject with a meaningful note</li><li>Confirm approval creates a task, not an inventory movement</li></ul>
  <div className="knowledge-checkpoint"><strong>Module 11 checkpoint</strong><p>Explain when a threshold task is generated, how forecast need is calculated, and which exact event moves stock from Storage to Picking.</p></div>
</section>}
