const reports=[['Stock on hand','Balance by SKU, warehouse, location, lot, expiry, and base UOM.'],['Inventory valuation','On hand × current standard cost, grouped by item and company valuation currency.'],['Stock aging','Positive balances grouped by the date stock first entered the item/location/lot.'],['Lot and expiry','Expiry-controlled balances, days remaining, and risk band.'],['Supplier performance','PO count and expected, accepted, held, damaged, and acceptance quantities.'],['Inventory movements','Recent ledger entries with quantity, location, movement type, and reference.'],['Receiving operations','Receipt-line expected and inspection outcomes.'],['Order fulfillment','Ordered, allocated, picked, and shipped quantities by order line.'],['Count variances','Expected, counted, variance, location, and count status.']];

export default function ModuleThirteen(){return <section className="panel" id="module-13">
  <div className="panel-heading"><div><p className="eyebrow">Module 13</p><h2>Reports, Dashboards, and Audit Logs</h2><p>Goal: turn live warehouse data into operational decisions, exportable evidence, and accountable transaction history.</p></div><span className="badge">Current lesson</span></div>
  <h3>Dashboard, report, and audit log</h3>
  <table className="data-table"><thead><tr><th>Tool</th><th>Question it answers</th></tr></thead><tbody><tr><td><strong>Dashboard</strong></td><td>What needs attention now, and what activity has happened today?</td></tr><tr><td><strong>Report</strong></td><td>What detailed balances or transactions support analysis and reconciliation?</td></tr><tr><td><strong>Audit log</strong></td><td>Who performed a controlled or security-sensitive action, when, and against which record?</td></tr></tbody></table>
  <div className="knowledge-note"><strong>Live-data rule:</strong> dashboard and report pages query current company data when opened. Export a dated copy when you need evidence of what was visible at a particular time.</div>
  <h3>Read the warehouse dashboard</h3>
  <p>Open <strong>Overview → Dashboard</strong>. Read it from top to bottom: attention queue, inventory KPIs, control queues, today’s operations, quick actions, then recent ledger activity.</p>
  <table className="data-table"><thead><tr><th>Indicator</th><th>Current calculation</th></tr></thead><tbody><tr><td><strong>Units on hand</strong></td><td>Sum of all inventory balances in the company, including non-available location types.</td></tr><tr><td><strong>SKUs in stock</strong></td><td>Distinct items having a positive balance.</td></tr><tr><td><strong>Orders to fulfill</strong></td><td>Orders whose status is not Dispatched.</td></tr><tr><td><strong>Stock accuracy</strong></td><td>100 − total absolute approved-count variance ÷ total absolute expected quantity × 100.</td></tr></tbody></table>
  <p>The attention total combines overdue approvals, open fulfillment exceptions, Counted records awaiting approval, and balances whose expiry is within 30 days. The operational control center separately links to approvals, exceptions, counts, packed orders, inbound receipts, and expiry reporting.</p>
  <h3>Today’s operations</h3>
  <table className="data-table"><thead><tr><th>Measure</th><th>Ledger basis since the database current date began</th></tr></thead><tbody><tr><td>Received</td><td>Receipt and inspection accepted/held/damaged positive movements</td></tr><tr><td>Picked</td><td>Positive pick-in movements at Packing</td></tr><tr><td>Shipped</td><td>Absolute quantity of shipment issues</td></tr><tr><td>Adjusted</td><td>Absolute adjustment and count-adjustment quantities</td></tr></tbody></table>
  <p>The bars compare relative quantities; they are not hourly productivity targets. Recent activity shows the latest four inventory ledger movements with SKU, location, reference, quantity, UOM, and local display time.</p>
  <h3>Dashboard interpretation boundaries</h3>
  <ul><li>Units on hand is a quantity total, not inventory value, and can mix different base UOMs.</li><li>Orders to fulfill currently includes every non-Dispatched status, so investigate Cancelled or otherwise inactive records before using it as a workload commitment.</li><li>The fixed dashboard expiry indicator uses 30 days and may include expired or zero balances.</li><li>Accuracy is based only on approved count lines and defaults to 100% when there is no usable approved-count denominator.</li><li>“Today” follows the database date boundary, while the browser formats displayed timestamps locally.</li></ul>
  <h3>Run standard reports</h3>
  <p>Open <strong>Insights → Reports</strong> and select a report:</p>
  <table className="data-table"><thead><tr><th>Report</th><th>Primary use</th></tr></thead><tbody>{reports.map(x=><tr key={x[0]}><td><strong>{x[0]}</strong></td><td>{x[1]}</td></tr>)}</tbody></table>
  <p>The report row count is shown above the table. Current report pages do not provide date, warehouse, item, or status filter controls; use the provided scope and export the data for further filtering when necessary.</p>
  <h3>Important report scopes</h3>
  <ul><li>The on-screen Inventory movements report covers the last 30 days and is limited to 500 rows.</li><li>The movements export returns the latest 1,000 ledger entries and does not use the same 30-day condition.</li><li>Stock aging includes only positive balances and uses the earliest positive ledger date for the item/location/lot.</li><li>Lot and expiry includes balances that have an expiry date, including expired records.</li><li>Count variances includes lines with an entered physical quantity, even before approval.</li><li>Reports are company-scoped; one subscribed company cannot query another company’s records.</li></ul>
  <h3>Inventory valuation and standard cost</h3>
  <pre className="knowledge-tree">Management inventory value = summed on-hand quantity × item standard cost</pre>
  <p>On the Inventory valuation report, Owners, Administrators, and Managers can maintain each item’s standard cost and the company’s three-character valuation currency. A cost update changes future report calculations but does not change physical quantities or recreate historical valuation snapshots.</p>
  <div className="knowledge-note"><strong>Valuation boundary:</strong> this is current standard-cost management valuation. It is not FIFO costing, landed cost, general-ledger posting, or an audited historical financial valuation.</div>
  <h3>Export CSV or PDF</h3>
  <p>Select <strong>Export CSV</strong> for spreadsheet analysis and data reconciliation. Select <strong>Export PDF</strong> for a readable, paginated management copy. Both exports are generated from live data at download time.</p>
  <ul><li>CSV preserves tabular fields and escapes embedded quotation marks.</li><li>PDF uses a simple fixed-width report layout and may clip very long row text.</li><li>Record the export date, purpose, company, and preparer outside the file when formal evidence is required.</li><li>Store exported inventory and user information only in approved secure locations.</li></ul>
  <h3>Configure alert thresholds</h3>
  <p>Open <strong>Insights → Alerts &amp; report automation</strong>. Owners, Administrators, and Managers can set:</p>
  <table className="data-table"><thead><tr><th>Threshold</th><th>Generated alert</th></tr></thead><tbody><tr><td>Expiry warning days</td><td>Positive balances expiring on or before the configured future date</td></tr><tr><td>Low-stock quantity</td><td>Positive individual balances at or below the quantity</td></tr><tr><td>Order overdue hours</td><td>Non-Dispatched orders older than the configured hours</td></tr><tr><td>Accuracy target</td><td>Approved-count accuracy below the target percentage</td></tr></tbody></table>
  <p>The background service evaluates active companies and records threshold events in <strong>Insights → Delivery &amp; alert center</strong>. These thresholds govern automated alerts; the dashboard’s fixed 30-day expiry figure is a separate calculation.</p>
  <h3>Instant and scheduled reports</h3>
  <p>Instant exports support Stock, Movements, Receiving, Fulfillment, Expiry, and Variances in CSV or PDF. A recurring schedule selects one of those reports, Daily/Weekly/Monthly frequency, format, and one or more email recipients separated by commas, semicolons, or spaces.</p>
  <p>The first run is scheduled one day, seven days, or 30 days after creation. Later monthly runs advance by one calendar month. Delivery sends recipients an authenticated Warevanta download link; the report is not attached to the email and is regenerated when an authorized signed-in user opens the link.</p>
  <div className="knowledge-note"><strong>Local environment:</strong> scheduled report email requires report delivery to be enabled plus a configured email provider and sender. When delivery is disabled locally, schedules can be created but report-delivery runs will not be processed.</div>
  <h3>Monitor delivery and retry</h3>
  <p>Delivery &amp; alert center shows the latest 100 scheduled runs with Scheduled, Sending, Sent, Failed, or Retry requested status, attempt, completion time, and error. Owners, Administrators, and Managers can select <strong>Retry</strong> on a failed run; this activates its schedule and makes it due immediately.</p>
  <p>A failed automatic delivery normally moves the schedule’s next attempt 15 minutes forward. Review the error before retrying—common local causes include email delivery not being configured or an invalid recipient.</p>
  <h3>Use audit history</h3>
  <p>Company users can open <strong>Administration → Users &amp; access</strong> and review the latest 30 workspace audit events. It shows time, actor, action, entity type, and stored details for security and controlled changes such as sign-in, password/MFA events, invitations, role changes, status changes, approval configuration, and exception resolution.</p>
  <p>The separate platform-administrator console at <strong>/admin#audit</strong> combines recent platform control changes with recent workspace security events across companies. This cross-company view is for the Warevanta platform administrator, not ordinary subscriber administration.</p>
  <table className="data-table"><thead><tr><th>Audit field</th><th>Meaning</th></tr></thead><tbody><tr><td>Time</td><td>When the recorded event was committed</td></tr><tr><td>Actor</td><td>User responsible, or System for automated work</td></tr><tr><td>Action</td><td>Normalized event name such as role changed</td></tr><tr><td>Record / area</td><td>Entity category affected by the event</td></tr><tr><td>Details</td><td>Available structured context; not every event stores the same fields</td></tr></tbody></table>
  <h3>Investigate a discrepancy</h3>
  <ol><li>Start with the dashboard indicator or report row that looks wrong.</li><li>Identify exact SKU, location, lot, expiry, reference, and date.</li><li>Use Inventory movements to reconstruct quantity changes.</li><li>Open the related receipt, order, count, return, or approval record.</li><li>Check audit history for controlled configuration or security changes.</li><li>Compare physical evidence and exported records.</li><li>Correct the source workflow or use an authorized adjustment—never edit evidence to make it agree.</li></ol>
  <h3>Current reporting boundaries</h3>
  <ul><li>Reports have fixed query scopes and no in-app custom report builder.</li><li>Scheduled emails contain download links rather than file attachments or immutable report snapshots.</li><li>There is no user-facing audit search, filter, full export, or retention control yet.</li><li>Workspace audit history shows only the latest 30 records on the Users page.</li><li>Not every ordinary inventory ledger movement also creates a separate audit-log row; the ledger itself is the movement history.</li><li>PDF export is a basic operational layout rather than a branded financial statement.</li></ul>
  <h3>Common mistakes</h3>
  <ul><li>Treating Units on hand as monetary inventory value.</li><li>Adding quantities with different UOMs and calling the result capacity or value.</li><li>Assuming dashboard and alert expiry thresholds are the same setting.</li><li>Using a live report as proof of an earlier period without saving a dated export.</li><li>Changing standard cost to correct a physical stock discrepancy.</li><li>Assuming a scheduled email contains a frozen attachment.</li><li>Retrying delivery repeatedly without resolving its configuration error.</li><li>Looking only at audit logs and ignoring the inventory ledger or source transaction.</li><li>Sharing exports through personal or unsecured storage.</li></ul>
  <h3>Practice checklist</h3>
  <ul className="knowledge-checklist"><li>Reconcile dashboard Units on hand to the Stock on hand report</li><li>Open each operational control queue from the dashboard</li><li>Trace one recent activity reference to its source workflow</li><li>Review all nine standard reports</li><li>Export Stock on hand to CSV and Count variances to PDF</li><li>Confirm the movements screen and export have different scopes</li><li>Review one item’s standard-cost valuation without changing quantity</li><li>Set safe training alert thresholds and observe the alert center</li><li>Create a scheduled training report using a controlled recipient</li><li>Confirm local email configuration before expecting delivery</li><li>Find a known role, approval, or security event in audit history</li></ul>
  <div className="knowledge-checkpoint"><strong>Module 13 checkpoint</strong><p>Explain why the dashboard is operational rather than financial, why an export is needed for point-in-time evidence, and when to use the inventory ledger instead of the audit log.</p></div>
</section>}
