const outcomes=[['Restock','Moves the full returned quantity from Hold to an active Storage or Picking location.','Stock becomes available again, subject to its status and expiry.'],['Scrap','Removes the full quantity from Hold with a return-scrap movement.','Company on hand decreases; no destination is used.'],['Ship to supplier','Removes the full quantity from Hold as a supplier-return issue.','Company on hand decreases; no destination is used.']];

export default function ModuleNine(){return <section className="panel" id="module-9">
  <div className="panel-heading"><div><p className="eyebrow">Module 9</p><h2>Returns and Reversals</h2><p>Goal: isolate returned stock, record the correct final outcome, and correct mistakes without deleting inventory history.</p></div><span className="badge">Current lesson</span></div>
  <h3>Two different return flows</h3>
  <table className="data-table"><thead><tr><th>Type</th><th>Stock origin</th><th>What Record return does</th></tr></thead><tbody><tr><td><strong>Customer return</strong></td><td>Goods arriving back from a customer</td><td>Adds the quantity to the selected Hold location for inspection.</td></tr><tr><td><strong>Supplier return</strong></td><td>Your existing Storage or Picking stock</td><td>Moves the quantity from its selected source location into Hold while a supplier decision or shipment is prepared.</td></tr></tbody></table>
  <div className="knowledge-note"><strong>Why Hold first?</strong> A returned item is not automatically saleable. Hold separates it from available stock until an authorized person inspects it and records a disposition.</div>
  <h3>Customer-return practice</h3>
  <p>Open <strong>Inventory control → Returns &amp; disposition</strong> and use:</p>
  <table className="data-table"><tbody><tr><th>Return number</th><td>TRAIN-RTN-001</td></tr><tr><th>Return type</th><td>Customer return</td></tr><tr><th>Customer or supplier</th><td>Training Customer</td></tr><tr><th>Reason</th><td>Customer rejected two cans at delivery</td></tr><tr><th>Item / quantity / unit</th><td>TRAIN-COLA-330 / 2 / EA</td></tr><tr><th>Barcode</th><td>Scan or enter a barcode registered to TRAIN-COLA-330</td></tr><tr><th>Lot and expiry</th><td>Enter the exact values printed on the returned stock</td></tr><tr><th>Quarantine location</th><td>An active Hold location, such as HOLD-01</td></tr></tbody></table>
  <ol><li>Match the physical item, barcode, lot, expiry, and quantity.</li><li>Record a specific return reason.</li><li>Select <strong>Record return</strong>.</li><li>Verify the return appears in the register with status <strong>Received</strong>.</li><li>Keep the stock physically in the selected Hold location.</li></ol>
  <p>The customer receipt increases company on hand, but it does not make the stock available for orders while it remains in Hold.</p>
  <h3>Supplier-return practice</h3>
  <p>Select <strong>Supplier return</strong>, identify the supplier, and choose the Storage or Picking location currently holding the exact item, lot, and expiry. Warevanta requires sufficient stock there. Recording the return moves it to Hold; it does not yet remove it from the company.</p>
  <div className="knowledge-note"><strong>Do not confuse the stages:</strong> Record return means “isolate for a return decision.” The later <strong>Ship to supplier</strong> disposition is what removes that stock from company on hand.</div>
  <h3>Inspect and choose one disposition</h3>
  <p>Inspect identity, packaging, seal, damage, lot, expiry, and any company quality rules. Then an Owner, Administrator, or Manager selects one final outcome for the entire return line:</p>
  <table className="data-table"><thead><tr><th>Disposition</th><th>Movement</th><th>Inventory result</th></tr></thead><tbody>{outcomes.map(x=><tr key={x[0]}><td><strong>{x[0]}</strong></td><td>{x[1]}</td><td>{x[2]}</td></tr>)}</tbody></table>
  <p>A destination is mandatory only for <strong>Restock</strong>, and it must be an active Storage or Picking location in the same warehouse. The current workflow disposes the full line; split outcomes should be entered as separate return records.</p>
  <h3>Reverse a return receipt</h3>
  <p>An Owner or Administrator may use <strong>Reverse receipt</strong> while the return is still Received. Use this only when the receipt itself was wrong—for example, duplicate entry, wrong item, or goods that never arrived.</p>
  <ul><li>The full quantity must still exist in the original Hold location.</li><li>A customer-return reversal removes the mistaken receipt from Hold.</li><li>A supplier-return reversal removes it from Hold and restores it to the original source.</li><li>A return cannot be reversed after Restock, Scrap, or Ship to supplier has been confirmed.</li><li>If company approval rules apply, the request goes to <strong>Control center → Approvals</strong> before execution.</li></ul>
  <h3>Reverse a dispatch</h3>
  <p>Open <strong>Outbound → Dispatch reversals</strong>. Only dispatched shipments are listed, and only an Owner or Administrator can submit the required reason. Depending on configured approval thresholds, Warevanta either reverses immediately or creates an approval request.</p>
  <p>When approved and executed, Warevanta posts stock back to the shipment’s Packing location, changes the shipment to Reversed, returns its cartons to Sealed, reduces the order’s shipped quantities, and returns the order to Packed. The shipment can then be corrected and dispatched again through the normal controls.</p>
  <div className="knowledge-note"><strong>Reversal is not deletion:</strong> Warevanta retains the original receipt or shipment and adds opposite ledger entries linked to the correction. This provides an auditable account of what happened, who corrected it, and why.</div>
  <h3>When to use each control</h3>
  <table className="data-table"><thead><tr><th>Situation</th><th>Correct action</th></tr></thead><tbody><tr><td>A customer physically sends goods back</td><td>Create a Customer return, then inspect and disposition it.</td></tr><tr><td>Stock will be sent back to a supplier</td><td>Create a Supplier return from its source, then choose Ship to supplier.</td></tr><tr><td>A return receipt was entered twice</td><td>Reverse the duplicate while it is still Received.</td></tr><tr><td>A dispatched shipment was posted by mistake</td><td>Request a dispatch reversal with a clear reason.</td></tr><tr><td>Stock is damaged during ordinary warehouse work</td><td>Use the appropriate adjustment or damage workflow—not a customer return.</td></tr></tbody></table>
  <h3>Common mistakes</h3>
  <ul><li>Restocking before inspection.</li><li>Selecting Customer return for inventory that is being sent to a supplier.</li><li>Using a Storage location where a Hold location is required.</li><li>Entering a lot or expiry different from the physical product.</li><li>Selecting a supplier-return source that lacks the exact lot and expiry quantity.</li><li>Choosing Restock without a destination.</li><li>Using reversal to change a legitimate business outcome instead of correcting an erroneous transaction.</li><li>Writing vague reasons such as “error” that do not support an audit.</li></ul>
  <h3>Practice checklist</h3>
  <ul className="knowledge-checklist"><li>Create customer return TRAIN-RTN-001 for 2 EA</li><li>Confirm its quantity is in Hold and excluded from availability</li><li>Inspect the physical item, lot, and expiry</li><li>Restock it to a Storage or Picking location</li><li>Confirm Hold decreased and the destination increased</li><li>Create a second small training return and reverse it before disposition</li><li>Confirm the original transaction and reversal both remain in history</li><li>Review Dispatch reversals without submitting one unless a safe training shipment is available</li></ul>
  <div className="knowledge-checkpoint"><strong>Module 9 checkpoint</strong><p>Explain the difference between a customer return, a supplier return, a disposition, and a reversal—and why a reversal must preserve the original transaction.</p></div>
</section>}
