const plans=[['Starter','₱1,200 monthly per user','Up to 3 users','1 warehouse'],['Growth','₱12,000 monthly','Up to 10 users','Up to 2 warehouses'],['Business','₱24,000 monthly','Up to 20 users','Up to 4 warehouses'],['Enterprise',"Let's talk",'Custom','Custom']];
const states=[['Trial','Workspace is in its introductory subscription state.'],['Active','Subscription is recognized as active.'],['Past due','Payment failed; a grace date may be shown while PayMongo retries.'],['Cancelled','Recurring subscription ended; billing suspension freezes workspace access.']];

export default function ModuleFifteen(){return <section className="panel" id="module-15">
  <div className="panel-heading"><div><p className="eyebrow">Module 15</p><h2>Platform Administration and Subscriptions</h2><p>Goal: understand who controls a subscriber workspace, who operates the Warevanta platform, and how plans, payments, limits, and access states interact.</p></div><span className="badge">Current lesson</span></div>
  <h3>Three separate levels of authority</h3>
  <table className="data-table"><thead><tr><th>Authority</th><th>Scope</th><th>Examples</th></tr></thead><tbody><tr><td><strong>Company Owner / Administrator</strong></td><td>One subscribed company</td><td>Users, roles, API keys, approval rules, plan selection, billing, and company operations.</td></tr><tr><td><strong>Company Manager / Operator / Viewer</strong></td><td>Assigned warehouse responsibilities inside one company</td><td>Operational management, execution, or viewing according to role.</td></tr><tr><td><strong>Warevanta Platform Administrator</strong></td><td>The multi-company service</td><td>Company access, subscription controls, user limits, verified recovery, and cross-company platform audit oversight.</td></tr></tbody></table>
  <div className="knowledge-note"><strong>Platform Administrator is not the same as Owner:</strong> platform access requires a separate protected platform-administrator record. Making a subscriber user an Owner or Administrator does not grant access to <code>/admin</code>.</div>
  <h3>Company data isolation</h3>
  <p>Each subscriber receives a private company identifier. Warehouses, locations, items, barcodes, inventory ledger, orders, receipts, users, reports, approvals, and API credentials are queried within that company scope.</p>
  <pre className="knowledge-tree">Warevanta platform{`\n`}├── Company A → users + warehouses + inventory + integrations{`\n`}└── Company B → separate users + warehouses + inventory + integrations</pre>
  <p>A subscription plan changes capacity and access state; it does not combine tenant data. Freezing or cancelling a company preserves its stored records.</p>
  <h3>Subscriber company overview</h3>
  <p>Open <strong>Administration → Company &amp; plan</strong> to review the company name, workspace slug, subscription status, plan, creation date, configured warehouses, user use, user limit, and Item Master count. Select <strong>Manage subscription</strong> to open billing.</p>
  <p>The workspace slug is the company’s internal tenant identifier. Do not treat it as a secret, but do not change company identity casually because integrations, support, and future cloud routing may depend on a stable identifier.</p>
  <h3>Current plan catalog</h3>
  <table className="data-table"><thead><tr><th>Plan</th><th>Listed price</th><th>User capacity</th><th>Warehouse offering</th></tr></thead><tbody>{plans.map(x=><tr key={x[0]}><td><strong>{x[0]}</strong></td><td>{x[1]}</td><td>{x[2]}</td><td>{x[3]}</td></tr>)}</tbody></table>
  <p>Annual billing is priced at ten monthly payments, representing two months at no additional cost. Enterprise creates a consultation request rather than online checkout.</p>
  <div className="knowledge-note"><strong>Capacity enforcement:</strong> user capacity is enforced when inviting or accepting users. Warehouse capacity is enforced when an Owner or Administrator creates a warehouse. A downgrade never deletes an existing warehouse, but no additional warehouse can be created while usage is at or above the plan allowance.</div>
  <h3>How user capacity is counted</h3>
  <p>Before a new invitation is created, Warevanta counts:</p>
  <pre className="knowledge-tree">Current company members + active, unaccepted, unrevoked invitations</pre>
  <p>If that reserved total has reached the company’s maximum, the invitation is blocked. Invitation acceptance checks the member count again. Expired or revoked invitations no longer reserve a slot.</p>
  <ul><li>Review pending invitations before requesting a larger plan.</li><li>Revoke invitations sent to the wrong person or no longer needed.</li><li>Changing an existing user’s role does not add another user.</li><li>Never raise a limit informally without confirming the subscription or authorized exception.</li></ul>
  <h3>Subscription states</h3>
  <table className="data-table"><thead><tr><th>Status</th><th>Meaning</th></tr></thead><tbody>{states.map(x=><tr key={x[0]}><td><strong>{x[0]}</strong></td><td>{x[1]}</td></tr>)}</tbody></table>
  <p>Workspace access is controlled separately by <strong>Access status</strong> and the subscription end date. An Active access state allows use; Frozen or a passed subscription end redirects users to Access suspended and blocks new sign-ins.</p>
  <h3>Choose or change a plan</h3>
  <p>Only a Company Owner or Administrator can submit a plan change. For Starter, Growth, or Business:</p>
  <ol><li>Select Monthly or Annual billing.</li><li>Review plan price and capacity.</li><li>Select <strong>Continue to PayMongo</strong>.</li><li>Complete payment authorization on the secure provider page.</li><li>Wait for the verified provider webhook to update the final subscription state, plan, billing cycle, capacity, and renewal details.</li></ol>
  <p>Starting another plan request cancels any earlier Pending payment change request in Warevanta. A provider response without a checkout URL remains Awaiting checkout or Pending until the provider reports the outcome.</p>
  <div className="knowledge-note"><strong>Local environment:</strong> the billing workflow is installed, but checkout requires PayMongo activation, secret credentials, webhook secret, and plan IDs. Until configured, the page reports that provider setup is required and no online plan change is applied.</div>
  <h3>Payment webhook behavior</h3>
  <p>Warevanta verifies PayMongo webhook signatures and records provider event IDs to prevent duplicate processing. Recognized outcomes include:</p>
  <ul><li><strong>Paid / Active:</strong> activates the subscription, applies the requested plan and capacity, clears billing suspension and payment failures, and restores access unless a platform administrator separately froze the company.</li><li><strong>Past due:</strong> records a failure, increments the failure count, and sets a seven-day grace date when none exists.</li><li><strong>Unpaid / Cancelled:</strong> marks the subscription Cancelled, enables billing suspension, freezes access, and sets the subscription end to the current date.</li><li><strong>Invoice events:</strong> update billing history with provider invoice number, amount, currency, status, period, payment date, and due date when supplied.</li></ul>
  <h3>Billing history</h3>
  <p>The Billing page lists the latest 20 provider invoices. Invoice number may link to a provider invoice page, and the table shows billing period, amount, currency, status, and issue date. Treat the provider invoice as billing evidence; warehouse inventory valuation reports are separate operational records.</p>
  <h3>Cancellation is destructive to access</h3>
  <p>When a connected subscription exists, an Owner or Administrator can select <strong>Cancel recurring subscription</strong>. The current workflow calls PayMongo, marks the company Cancelled, stops recurring billing, freezes the workspace immediately, sets the end date to today, and records an audit event.</p>
  <div className="knowledge-note"><strong>Before cancelling:</strong> export required inventory, reports, audit evidence, invoices, and integration records; notify users; revoke or coordinate external integrations; and confirm how restoration will be handled. Cancellation does not delete data, but users lose normal workspace access.</div>
  <h3>Platform company controls</h3>
  <p>A separately authorized Platform Administrator opens <code>https://localhost/admin</code>. For each company, the console shows name, slug, creation date, users, user limit, active sessions, access, subscription, plan, end date, and internal notes. It can update:</p>
  <table className="data-table"><thead><tr><th>Control</th><th>Effect</th></tr></thead><tbody><tr><td><strong>Access: Active / Frozen</strong></td><td>Administrative access decision. Freezing revokes normal company sessions immediately.</td></tr><tr><td><strong>Subscription status</strong></td><td>Trial, Active, Past due, or Cancelled display/control state.</td></tr><tr><td><strong>Plan</strong></td><td>Starter, Growth, Business, or Enterprise designation.</td></tr><tr><td><strong>User limit</strong></td><td>Maximum from 1 to 10,000 used by invitation and acceptance checks.</td></tr><tr><td><strong>Subscription end</strong></td><td>Date used by sign-in and application access checks.</td></tr><tr><td><strong>Administrator notes</strong></td><td>Up to 500 characters of internal platform context.</td></tr></tbody></table>
  <p>Every save records the before and after values in the platform audit log. Platform notes should be factual, minimal, and free of passwords, payment-card data, API keys, or unnecessary personal information.</p>
  <h3>Two independent freeze causes</h3>
  <p>Warevanta records an administrative freeze and a billing suspension separately. Effective access remains Frozen when either applies.</p>
  <pre className="knowledge-tree">Effective Frozen = Platform admin freeze OR Billing suspension OR passed subscription end</pre>
  <p>Changing Access to Active in the platform console cannot override an unresolved billing suspension. A successful Active payment webhook clears billing suspension but preserves a separate platform-admin freeze.</p>
  <h3>What freezing does</h3>
  <ul><li>Revokes normal active sessions when initiated by the platform control.</li><li>Blocks normal company sign-in.</li><li>Redirects existing workspace navigation to Access suspended.</li><li>Preserves company records in the database.</li><li>Does not grant subscriber users access to the platform console.</li><li>Requires resolution of every applicable freeze cause before normal access returns.</li></ul>
  <h3>Platform user recovery</h3>
  <p>The restricted <code>/admin/users</code> page can search users across companies and generate a one-time temporary password for verified recovery or local testing. It revokes all of the user’s sessions, requires a password change at next sign-in, shows the temporary password only once, disables caching of that response, and creates a platform audit event.</p>
  <div className="knowledge-note"><strong>Production caution:</strong> cross-company password recovery is exceptional high-risk authority. Production readiness must define identity verification, support authorization, staff access, monitoring, and incident response before this control is used with real subscribers.</div>
  <h3>Platform audit responsibilities</h3>
  <p>The console combines the latest platform control events and recent workspace audit events across companies. A platform administrator should regularly review company freezes, user recovery, limit changes, subscription changes, unusual actors, and actions outside approved support cases.</p>
  <h3>Current subscription boundaries</h3>
  <ul><li>PayMongo checkout and email require external configuration and are not active merely because the screens exist.</li><li>Warehouse-count offerings are not yet enforced as hard creation limits.</li><li>There is no subscriber self-service billing-contact editor or payment-method portal in the current screen.</li><li>There is no automated proration explanation, refund workflow, tax computation, or downloadable internal invoice generator.</li><li>The platform console can manually set plan and subscription state independently of provider state, so operating procedures and reconciliation are essential.</li><li>Subscription end, billing suspension, and administrative freeze must be reconciled as separate controls.</li></ul>
  <h3>Common mistakes</h3>
  <ul><li>Assuming Company Administrator grants Platform Administrator access.</li><li>Increasing user capacity without confirming the contracted plan.</li><li>Forgetting that pending invitations consume user slots.</li><li>Changing the plan display manually and assuming PayMongo billing also changed.</li><li>Setting Access Active while billing suspension is unresolved.</li><li>Freezing the wrong company without checking its slug and support case.</li><li>Putting secrets or sensitive payment details in administrator notes.</li><li>Cancelling before exporting required evidence.</li><li>Sharing platform-recovery temporary passwords in insecure channels.</li><li>Treating preserved frozen data as deleted or lost.</li></ul>
  <h3>Practice checklist</h3>
  <ul className="knowledge-checklist"><li>Open Company &amp; plan and identify your tenant slug</li><li>Review current plan, subscription status, user use, warehouse count, and SKU count</li><li>Compare members plus active invitations with the displayed user limit</li><li>Open Billing and review provider readiness without starting a real payment</li><li>Explain Trial, Active, Past due, Cancelled, Active access, and Frozen access</li><li>If authorized as Platform Administrator, open /admin and identify the correct training company</li><li>Review controls without freezing a live testing workspace</li><li>Find recent platform and workspace events in the audit panel</li><li>Review /admin/users recovery safeguards without resetting a user unnecessarily</li><li>Describe the export and communication checklist required before cancellation</li></ul>
  <div className="knowledge-checkpoint"><strong>Module 15 checkpoint</strong><p>Explain the difference between Company Owner and Platform Administrator, how pending invitations affect capacity, and why setting Access Active may not restore a billing-suspended company.</p></div>
</section>}
