const statuses=[['New','Order and lines can still be reviewed or extended.'],['Allocated','Inventory is reserved and guided pick tasks exist.'],['Picking','At least one pick is complete while other picks remain.'],['Picked','All assigned picks are complete at the packing location.'],['Packing','Some picked tasks are verified into cartons.'],['Packed','All tasks are verified into cartons and ready for sealing/dispatch controls.'],['Dispatched','Shipment is confirmed and inventory has left the warehouse.']];

export default function ModuleEight(){return <section className="panel" id="module-8">
  <div className="panel-heading"><div><p className="eyebrow">Module 8</p><h2>Orders, Picking, Packing, and Dispatch</h2><p>Goal: turn customer demand into reserved work, verify every physical movement, and issue inventory only when a sealed shipment leaves the warehouse.</p></div><span className="badge">Current lesson</span></div>
  <h3>The outbound lifecycle</h3>
  <pre className="knowledge-tree">Sales order → Allocate → Pick → Pack into carton{`\n`}→ Seal carton → Dispatch → Shipment history</pre>
  <h3>Create a training sales order</h3>
  <p>Open <strong>Outbound → Orders</strong> and create:</p>
  <table className="data-table"><tbody><tr><th>Order number</th><td>TRAIN-SO-001</td></tr><tr><th>Customer</th><td>Training Customer</td></tr><tr><th>Warehouse</th><td>The warehouse holding TRAIN-COLA-330</td></tr><tr><th>Item</th><td>TRAIN-COLA-330</td></tr><tr><th>Quantity / UOM</th><td>6 / EA</td></tr><tr><th>Priority</th><td>Normal</td></tr><tr><th>Requested ship date</th><td>A future training date</td></tr></tbody></table>
  <p>A unique order number is required. Use the base UOM for this exercise. While the order is New, open it to add more lines if required. Review the customer, warehouse, items, quantities, priority, and date before release.</p>
  <h3>Requesting-store orders</h3>
  <p>A company with several stores should create each destination in <strong>Master data → Requesting stores</strong>. Invite store personnel with a dedicated <strong>Store Viewer</strong>, <strong>Store Operator</strong>, or <strong>Store Manager</strong> access profile and select their store before sending the invitation.</p>
  <p>At the next sign-in, the store user opens the restricted <strong>Store Inventory Portal</strong>. The user can request stock, receive dispatched deliveries, check approved store availability, and submit returns, store-to-store transfers, and miscellaneous issues. The store cannot see or transact against another store except selecting an active destination for a transfer.</p>
  <ol><li>Create and activate the requesting store in <strong>Master data → Requesting stores</strong>, then select its <strong>Default fulfilling warehouse</strong>. The warehouse must be active and within your approved access scope.</li><li>Open <strong>Administration → Users &amp; access</strong>.</li><li>Choose the correct Store access profile, select the requesting store, and send the invitation.</li><li>After the employee accepts it, Warevanta assigns the store automatically and directs the user to the Store Portal.</li><li>A Store Operator adds one or more item lines, chooses an active request UOM for each line, enters quantity and required date, then submits. Warevanta generates one SRQ reference, retains entered units, and normalizes demand to base units.</li><li>For a Virtual kit, the Store Portal shows component-driven <strong>complete kits available</strong> for the assigned fulfilling warehouse and accepts the parent request in KIT.</li><li>A different Store Manager opens <strong>Home → Fulfillment → Stock request history</strong> and selects <strong>Approve</strong> or <strong>Reject</strong> in the pending row&apos;s Actions column; self-approval is blocked.</li><li>Marking an inbox notification read does not approve the request. It only clears the unread indicator.</li><li>Store approval notifies management users assigned to the fulfilling warehouse. They open <strong>Outbound → Store requests</strong> and select <strong>Accept and release</strong> or <strong>Reject</strong>. Acceptance is blocked when required component ATP cannot build the requested VKIT quantity.</li><li>Only a warehouse-accepted request appears in <strong>Outbound → Order management</strong>. Changing the store route affects new requests; existing requests retain their original warehouse.</li><li>The warehouse allocates the parent VKIT into required component demand, then creates component-level pick tasks. Mobile users scan each actual component or approved substitute shown by the task.</li><li>The warehouse packs and dispatches the released request while the sales order retains the customer-facing VKIT line.</li><li>The store classifies every delivered line as Accepted, Short, or Damaged and submits the receipt.</li><li>An Owner, Administrator, Manager, or assigned Store Manager approves or rejects the receipt.</li><li>Only an approved receipt increases Store availability.</li></ol>
  <div className="knowledge-note"><strong>Separate inventory ledgers:</strong> warehouse dispatch reduces warehouse inventory. Store receipt approval increases the store inventory subledger; it never recreates warehouse stock. Accepted + Short + Damaged must equal the dispatched quantity for every receipt line.</div>
  <div className="knowledge-note"><strong>VKIT partial release:</strong> leave partial release unchecked when the Store requires one complete delivery. When explicitly authorized, Warevanta floors component availability to whole kits, releases that quantity, and moves the remainder to a linked backorder. Re-run allocation on the backorder after component replenishment; incomplete kits never proceed to picking.</div>
  <div className="knowledge-note"><strong>Backorder lifecycle:</strong> linked backorders start as Waiting, change automatically to Ready when replenished components can build every outstanding kit, then move through Released and Fulfilled. Warehouse managers receive a readiness notification and may allocate or cancel an unallocated backorder with a recorded reason. The Store Portal shows the parent request and current backorder status.</div>
  <div className="knowledge-note"><strong>Backorder exceptions:</strong> open <a href="/app/orders/backorders"><strong>VKIT backorder exceptions</strong></a> from Order Management to filter Waiting, Ready, Overdue, Released, Fulfilled, or Cancelled demand. Review each deficient component, its ATP, and the best active substitute before changing the commitment date. Every revised date requires a reason, keeps the original date, writes an audit record, and notifies the warehouse and Store.</div>
  <div className="knowledge-note"><strong>Escalation:</strong> the hosted background worker checks VKIT backorders every minute. Due soon, overdue, and critical stages each create at most one notification per backorder. Open the exception center from any Order Management screen, enter a resolution or follow-up note, and acknowledge the alert. Acknowledgement clears the related warehouse notification but does not change, allocate, or cancel the order.</div>
  <div className="knowledge-note"><strong>Multi-option substitution:</strong> open <a href="/app/orders/backorders/substitutions"><strong>Substitution workbench</strong></a>. Warevanta ranks every active direct substitute, reverse reciprocal link, and supersession-chain destination by sufficient ATP, path depth, relationship priority, and SKU. Review the cumulative conversion ratio, required substitute quantity, ATP, approval requirement, and path depth before selecting an option. Cycles are excluded and paths stop at eight relationships. If stock changes, allocation tries the selected approved path first and then the next approval-free ranked option. After picking begins the order is no longer eligible for substitution. Mobile picking always requires the barcode of the actual allocated item.</div>
  <div className="knowledge-note"><strong>Shortage sourcing:</strong> when exact stock and eligible substitutes still cannot cover demand, open <a href="/app/orders/shortage-sourcing"><strong>Shortage sourcing</strong></a> and select <strong>Generate recommendations</strong>. Warevanta checks another warehouse, active Store stock, open inbound POs, then external procurement. Review quantity, source, and expected date before accepting or rejecting with a reason. Acceptance creates a traceable draft supply-transfer document, links an existing PO, or creates a native draft PO using the selected active supplier. Re-running generation never duplicates an existing pending recommendation for the same order and item.</div>
  <div className="knowledge-note"><strong>Execute a shortage supply transfer:</strong> open <a href="/app/orders/shortage-transfers"><strong>Supply transfers</strong></a>. A Manager approves warehouse-sourced work; an assigned Store Manager approves Store-sourced work. The source scans the exact active location and registered item barcode before each partial or full dispatch. Inventory leaves the source at dispatch and enters the destination only after a destination user scans the receiving location and item. Receive no more than the quantity in transit. A Manager may cancel before dispatch or reverse a fully received transfer with a reason and sufficient destination stock.</div>
  <div className="knowledge-note"><strong>Automatic allocation after replenishment:</strong> accepted supply transfers are received directly into an active Storage or Picking location and immediately recheck the originating order. Purchase-order supply rechecks after accepted inventory is put away. Warevanta allocates only when every standard line or required VKIT component is available, reserves the exact lots by FIFO/FEFO/LIFO, creates pick tasks, links them to the supply document, and notifies the warehouse and Store. Open <a href="/app/orders/replenishment-allocation"><strong>Replenishment allocation</strong></a> to inspect Pending or Exception jobs and retry with a reason after correcting stock, location, or order state.</div>
  <div className="knowledge-note"><strong>Operations control:</strong> open <a href="/app/orders/operations-control"><strong>Fulfillment operations control</strong></a> to manage replenishment exceptions by severity, SLA, warehouse, Store, item, domain, status, and date. Assign an eligible owner, acknowledge active investigation, resolve with evidence, or reopen when the issue returns. Expand the end-to-end timeline to trace recommendation, transfer, receipt, allocation, picking, and dispatch. Export the filtered queue to CSV and use the KPI cards to review conversion, allocation success, failures, and transfer lead time.</div>
  <h3>Store portal roles</h3>
  <ul><li><strong>Store Viewer:</strong> read availability, requests, deliveries, and transaction history.</li><li><strong>Store Operator:</strong> Viewer access plus request stock, receive deliveries, and submit returns, transfers, and miscellaneous issues.</li><li><strong>Store Manager:</strong> Operator access plus approve or reject receipts and store inventory transactions for the assigned store.</li></ul>
  <p>The Store Portal includes Home, Counts, Locators, Knowledge base, and Sign out. Counts record system-versus-physical quantity for review. Locators maintain receiving, backroom, sales-floor, hold, and damaged-stock references.</p>
  <h3>Store returns, transfers, and miscellaneous issues</h3>
  <p>In the Store Inventory Portal, select the exact item, quantity, UOM, lot, and expiry held by the store. Enter a meaningful reason, then submit. Warevanta generates the return, transfer, or miscellaneous-issue reference automatically. An assigned Store Manager reviews it in the Store Portal; internal management can review pending store work from <strong>Store approvals</strong>.</p>
  <ul><li><strong>Return stock:</strong> removes approved quantity from store availability. A separate warehouse receiving process is required if the physical return comes back into warehouse stock.</li><li><strong>Transfer stock:</strong> removes quantity from the source store and adds the same quantity to the selected active destination store in one transaction group.</li><li><strong>Miscellaneous issue:</strong> removes stock for an authorized non-sales use such as damage, sampling, consumption, or write-off.</li><li>Approval is rejected if the source store no longer has enough of the exact item, lot, and expiry.</li><li>Rejected requests never change inventory.</li></ul>
  <h3>Release and allocate</h3>
  <p>Select <strong>Release and allocate all lines</strong>. Warevanta reserves matching inventory from Storage or Picking locations, follows the item allocation method, and creates pick tasks to an active Packing location.</p>
  <ul><li>FIFO favors the oldest eligible stock.</li><li>FEFO favors the earliest-expiring eligible lot.</li><li>LIFO favors the newest eligible stock.</li><li>Existing allocations reduce what remains available for another order.</li><li>Every order line must have sufficient stock or allocation rolls back.</li><li>An active Packing location is required.</li></ul>
  <div className="knowledge-note"><strong>Reservation is not a physical movement:</strong> allocation increases Reserved and reduces ATP, but On hand does not change until warehouse work is executed.</div>
  <h3>How kits and substitutes allocate</h3>
  <ul><li><strong>Standard, spare part, and stocked kit:</strong> Warevanta first allocates the ordered SKU as finished inventory.</li><li><strong>Virtual kit:</strong> Warevanta multiplies each required component quantity by the ordered kit quantity and creates component pick tasks.</li><li><strong>Automatic substitute:</strong> exact stock is used first; remaining demand can use active substitutes by priority, date, and conversion ratio.</li><li><strong>Controlled substitute:</strong> allocation pauses and creates an approval request only when that substitute can cover the remaining demand.</li></ul>
  <p>After a controlled substitution is approved, return to the New sales order and select <strong>Release and allocate all lines</strong> again. The authorization applies only to that order. Pick tasks always show the actual physical SKU and quantity to scan. The order line keeps its original requested kit or item quantity.</p>
  <div className="knowledge-note"><strong>Quantity integrity:</strong> picking three different component quantities for one virtual kit does not make the order show three shipped lines. The sales order reports the requested kit quantity; inventory movements report the actual component or substitute quantities.</div>
  <h3>Read the guided pick task</h3>
  <p>Each task states the quantity, UOM, item, exact source, Packing destination, lot, and expiry. A line can produce several tasks when its quantity must be supplied by multiple locations or lots.</p>
  <h3>Confirm picking</h3>
  <p>Use the order page or <strong>Mobile work → Pick &amp; pack → Pick queue</strong>. For every task:</p>
  <ol><li>Travel to the assigned source location.</li><li>Confirm the displayed SKU, lot, expiry, and quantity.</li><li>Scan the assigned source-location code.</li><li>Scan a barcode registered to the assigned item.</li><li>Physically move the quantity to the Packing location.</li><li>Select <strong>Confirm pick</strong>.</li></ol>
  <p>Picking creates a balanced movement: a negative entry at the source and an equal positive entry at Packing. Company on hand is unchanged.</p>
  <h3>Report a short pick</h3>
  <p>If stock is missing, damaged, wrong, or inaccessible, do not confirm a false pick. Open <strong>Cannot complete this pick?</strong>, select the reason, add a useful note, and report the exception for manager resolution.</p>
  <h3>Create the packing carton</h3>
  <p>Before mobile packing, open <strong>Outbound → Packing cartons</strong>. Create an open carton for the same order using a unique identifier such as <code>TRAIN-CTN-001</code>.</p>
  <div className="knowledge-note"><strong>Carton ownership:</strong> a carton belongs to one order. A pick task cannot be verified into a carton created for another order or into a carton that is already sealed.</div>
  <h3>Verify packing</h3>
  <p>Open the Pack queue. For every completed pick:</p>
  <ol><li>Scan the assigned Packing location.</li><li>Select an open carton belonging to the order.</li><li>Scan the item barcode again.</li><li>Place the physical quantity in that carton.</li><li>Select <strong>Verify into carton</strong>.</li></ol>
  <p>Packing verification links the picked task and quantity to the carton. It does not issue stock from the warehouse; inventory remains at the Packing location.</p>
  <h3>Seal and label the carton</h3>
  <p>Return to Packing cartons. An empty carton cannot be sealed. Enter actual weight, length, width, and height, then select <strong>Seal carton</strong>. Print the carton label and attach it to the correct physical carton.</p>
  <table className="data-table"><tbody><tr><th>Weight</th><td>Actual packed weight in kilograms</td></tr><tr><th>Dimensions</th><td>Actual length × width × height in centimeters</td></tr><tr><th>Carton label</th><td>Identifies carton, order, customer, contents, weight, and dimensions</td></tr></tbody></table>
  <h3>Dispatch the order</h3>
  <p>All tasks must be packed and all participating cartons must be sealed. In Mobile dispatch:</p>
  <ol><li>Open the packed order.</li><li>Scan the assigned Packing location.</li><li>Enter the carrier.</li><li>Scan or enter the tracking/reference number.</li><li>Verify the physical cartons and paperwork.</li><li>Select <strong>Confirm dispatch</strong>.</li></ol>
  <p>Dispatch creates the shipment, marks sealed cartons Dispatched, changes the order to Dispatched, updates shipped quantities, and posts a negative shipment issue from Packing. This is the point at which company on-hand inventory decreases.</p>
  <h3>Print and retain shipment evidence</h3>
  <p>After dispatch, open the shipment label. It includes the shipment number, order, customer, carrier, tracking reference, contents, origin, and dispatch time. Recent shipments remain available from Mobile dispatch for reprinting.</p>
  <h3>Order statuses</h3>
  <table className="data-table"><thead><tr><th>Status</th><th>Meaning</th></tr></thead><tbody>{statuses.map(x=><tr key={x[0]}><td><strong>{x[0]}</strong></td><td>{x[1]}</td></tr>)}</tbody></table>
  <h3>Inventory effect by stage</h3>
  <table className="data-table"><thead><tr><th>Stage</th><th>On hand</th><th>Reserved / location effect</th></tr></thead><tbody><tr><td>Allocate</td><td>No change</td><td>Reserved increases; ATP decreases</td></tr><tr><td>Pick</td><td>No company-total change</td><td>Stock moves Source → Packing</td></tr><tr><td>Pack / seal</td><td>No change</td><td>Tasks are linked to sealed cartons</td></tr><tr><td>Dispatch</td><td>Decreases</td><td>Shipment issue removes stock from Packing</td></tr></tbody></table>
  <h3>Pick waves</h3>
  <p>Open <strong>Outbound → Pick waves</strong> to group all unassigned pending picks in a warehouse under a unique wave number. Waves organize work; the same location and item scan controls still apply to every task.</p>
  <h3>Operational responsibility</h3>
  <p>Open <strong>Outbound → Order orchestration</strong> for the daily fulfillment overview. Its summary shows active orders, pending Store requests, blocked orders, open exceptions, overdue exceptions, and allocation failures. Select an order from the fulfillment work queue to perform transactional work. Managers use <strong>Operations → Operations control</strong> for exception ownership, SLA escalation, timelines, and reporting.</p>
  <p className="knowledge-note"><strong>Release planning:</strong> open <strong>Outbound → Release planning</strong> to rank scoped orders by priority, required date, fulfillment state, and exception risk. Follow the recommended action for Ready to release, Waiting for stock, Blocked, At risk, Ready to wave, or Ready to dispatch work. To build a pick wave, select only <strong>Ready to wave</strong> orders from the same warehouse, enter the planning reason, and select <strong>Create wave from selected</strong>. Warevanta generates the wave reference and records the included orders, tasks, manager, score, and recommendation.</p>
  <p className="knowledge-note"><strong>Navigation shortcuts:</strong> managers can open <strong>Operations → Store approvals</strong> directly for pending Store requests, delivery receipts, returns, transfers, and miscellaneous issues. Open <strong>Inbound → Store return receiving</strong> to receive approved VKIT components into an authorized quarantine location. Store-user roles and scopes are maintained only through <strong>Administration → Users &amp; access</strong>; old Store-access bookmarks redirect there.</p>
  <p>Owners, administrators, or managers normally review demand and release work. Operators execute permitted picking, packing, sealing, and dispatch scans. Assign every internal user to the appropriate warehouse from <strong>Administration → Users &amp; access → Access profiles</strong>. Warevanta validates that assignment when an order is allocated, picked, short-picked, packed, placed in a carton, dispatched, reversed, or opened through an order or printable-label URL. An Owner retains access to every warehouse.</p>
  <p className="knowledge-note"><strong>What each user sees:</strong> Orders, mobile pick and pack, carton boards, mobile dispatch, recent shipments, pick waves, exceptions, reversals, and shipping manifests are limited to approved warehouses. If work is missing from a queue, first verify the user’s warehouse access profile instead of recreating the transaction.</p>
  <h3>Common mistakes</h3>
  <ul><li>Allocating before checking the customer, warehouse, lines, and quantities.</li><li>Assuming Reserved stock has physically moved.</li><li>Picking from a convenient location instead of the assigned source.</li><li>Scanning the receipt label instead of the item barcode.</li><li>Confirming a short or damaged pick instead of reporting an exception.</li><li>Trying to pack before creating an open carton.</li><li>Selecting a carton belonging to another order.</li><li>Sealing an empty carton or entering estimated dimensions as actual measurements.</li><li>Dispatching before all cartons are sealed.</li><li>Using a vague carrier or tracking reference that cannot support delivery investigation.</li></ul>
  <h3>Practice checklist</h3>
  <ul className="knowledge-checklist"><li>Create TRAIN-SO-001 for 6 EA of TRAIN-COLA-330</li><li>Review ATP before allocation</li><li>Release and allocate all lines</li><li>Confirm Reserved increased while company on hand stayed unchanged</li><li>Complete the assigned source-location and item scans</li><li>Create carton TRAIN-CTN-001</li><li>Verify picked stock into that carton</li><li>Enter actual measurements and seal the carton</li><li>Print or display the carton label</li><li>Dispatch with a packing-location scan, carrier, and tracking reference</li><li>Review the shipment label and shipment-issue movement</li><li>Confirm final order, carton, and inventory statuses</li></ul>
  <div className="knowledge-checkpoint"><strong>Module 8 checkpoint</strong><p>Explain when Reserved changes, when stock physically moves to Packing, and the exact event that reduces company on-hand inventory.</p></div>
  <div className="knowledge-note"><strong>Carrier and delivery control:</strong> owners and administrators maintain services in <strong>Master data → Carriers &amp; routes</strong>; managers assign the preferred service for each Store and warehouse. After dispatch, use <strong>Outbound → Delivery tracking</strong> to record pickup, transit, out-for-delivery, delivered, failed, or returned milestones. Delivered updates require recipient and proof references. Missed delivery promises create an operational exception.</div>
  <div className="knowledge-note"><strong>Carrier planning and handover:</strong> Mobile Dispatch recommends the Store route. Save the carrier plan before dispatch; a non-preferred service requires an override reason. Warevanta calculates the cut-off and expected delivery, then carries those promises into the shipment. Create manifests by carrier service and pickup date, and close handover only after scanning the carrier reference.</div>
  <div className="knowledge-note"><strong>Carrier integrations:</strong> owners and administrators configure each active service in <strong>Master data → Carrier integrations</strong>. Manual mode requires no external account. API and Hybrid modes enqueue booking work at dispatch and retry transient failures with exponential backoff; five failures create a dead-letter exception. Webhook and Hybrid modes verify the carrier&apos;s HMAC-SHA256 signature, reject duplicate event IDs, map external milestones, and update delivery proof.</div>
</section>}
