import {getSession} from "../../../../lib/auth";
import {tenantRows} from "../../../../lib/db";
export const dynamic="force-dynamic";
type Row={id:string;order_no:string;sku:string;warehouse:string;shortage_quantity:string;recommended_quantity:string;uom:string;recommended_action:string;source:string|null;expected_available_date:string|null;status:string;document_reference:string|null;review_note:string|null};type Supplier={id:string;code:string;name:string};
export default async function ShortageSourcing({searchParams}:{searchParams:Promise<{generated?:string;decided?:string;error?:string}>}){
 const s=await getSession(),q=await searchParams;const[rows,suppliers]=s?await Promise.all([
  tenantRows<Row>(s.companyId,`SELECT r.id,o.order_no,i.sku,w.name warehouse,r.shortage_quantity::text,r.recommended_quantity::text,r.uom,r.recommended_action,coalesce(sw.name,ss.name,p.po_no) source,r.expected_available_date::text,r.status,r.document_reference,r.review_note FROM shortage_sourcing_recommendations r JOIN sales_orders o ON o.company_id=r.company_id AND o.id=r.order_id JOIN items i ON i.company_id=r.company_id AND i.id=r.item_id JOIN warehouses w ON w.company_id=r.company_id AND w.id=r.warehouse_id LEFT JOIN warehouses sw ON sw.company_id=r.company_id AND sw.id=r.source_warehouse_id LEFT JOIN requesting_stores ss ON ss.company_id=r.company_id AND ss.id=r.source_store_id LEFT JOIN purchase_orders p ON p.company_id=r.company_id AND p.id=r.source_purchase_order_id WHERE r.company_id=$1 AND ($2='owner' OR EXISTS(SELECT 1 FROM user_warehouse_assignments a WHERE a.company_id=r.company_id AND a.user_id=$3 AND a.warehouse_id=r.warehouse_id)) ORDER BY r.status='pending' DESC,r.created_at DESC LIMIT 200`,[s.companyId,s.role,s.userId]),
  tenantRows<Supplier>(s.companyId,`SELECT id,code,name FROM suppliers WHERE company_id=$1 AND status='active' ORDER BY name`,[s.companyId])
 ]):[[],[]];
 return <div className="app-content"><div className="page-heading"><div><h1>Shortage sourcing</h1><p>Turn unresolved order shortages into ranked transfer, inbound-supply, or procurement actions.</p></div><form method="post" action="/api/orders/shortages/generate"><button className="button button-primary">Generate recommendations</button></form></div>
 {q.generated&&<div className="success-banner">Generated {q.generated} new recommendation(s). Existing pending recommendations were not duplicated.</div>}{q.decided&&<div className="success-banner">Recommendation decision recorded and its supply document created when accepted.</div>}{q.error&&<div className="form-error">The sourcing action failed. Check current shortage, warehouse access, active supplier, quantity, and source availability.</div>}
 <section className="panel"><table className="data-table"><thead><tr><th>Demand</th><th>Shortage</th><th>Recommendation</th><th>Expected</th><th>Status / document</th><th>Decision</th></tr></thead><tbody>{rows.length?rows.map(x=><tr key={x.id}><td><strong>{x.order_no}</strong><small>{x.sku} · {x.warehouse}</small></td><td>{x.shortage_quantity} {x.uom}</td><td><strong>{x.recommended_action.replaceAll("_"," ")}</strong><small>{x.recommended_quantity} {x.uom}{x.source?` from ${x.source}`:""}</small></td><td>{x.expected_available_date||"Set during review"}</td><td><span className="badge">{x.status}</span>{x.document_reference&&<small>{x.document_reference}</small>}{x.review_note&&<small>{x.review_note}</small>}</td><td>{x.status==="pending"?<form className="form-stack compact-form" method="post" action={`/api/orders/shortages/${x.id}/decision`}>{x.recommended_action==="purchase_order"&&<><select name="supplierId" required><option value="">Select supplier</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.code} — {s.name}</option>)}</select><input type="date" name="expectedDate"/></>}<input name="quantity" type="number" min="0.000001" max={x.shortage_quantity} step="any" defaultValue={x.recommended_quantity} required/><input name="note" placeholder="Decision reason" required minLength={2}/><div className="form-row"><button className="button button-primary" name="decision" value="accept">Accept</button><button className="button button-secondary" name="decision" value="reject">Reject</button></div></form>:"—"}</td></tr>):<tr><td className="empty-cell" colSpan={6}>No sourcing recommendations. Generate after an order or VKIT backorder has an unresolved shortage.</td></tr>}</tbody></table></section></div>
}
