import Link from 'next/link';
import {getSession} from '../../../lib/auth';
import {tenantRows} from '../../../lib/db';
export const metadata={title:'Receiving'};export const dynamic='force-dynamic';
type Receipt={id:string;receipt_no:string;supplier:string;status:string;expected_date:string|null;item:string;expected_quantity:string;uom:string};
type Warehouse={id:string;name:string};type Item={id:string;sku:string;description:string;base_uom:string};

export default async function Receiving({searchParams}:{searchParams:Promise<{error?:string}>}){
  const s=await getSession();const {error}=await searchParams;
  const [receipts,warehouses,items]=s?await Promise.all([
    tenantRows<Receipt>(s.companyId,`SELECT r.id,r.receipt_no,r.supplier,r.status,r.expected_date::text,i.sku||' — '||i.description AS item,rl.expected_quantity::text,rl.uom FROM inbound_receipts r JOIN inbound_receipt_lines rl ON rl.company_id=r.company_id AND rl.receipt_id=r.id JOIN items i ON i.company_id=r.company_id AND i.id=rl.item_id WHERE r.company_id=$1 AND ($2='owner' OR EXISTS(SELECT 1 FROM user_warehouse_assignments a WHERE a.company_id=r.company_id AND a.user_id=$3 AND a.warehouse_id=r.warehouse_id)) ORDER BY r.created_at DESC`,[s.companyId,s.role,s.userId]),
    tenantRows<Warehouse>(s.companyId,`SELECT id,name FROM warehouses w WHERE company_id=$1 AND active=true AND ($2='owner' OR EXISTS(SELECT 1 FROM user_warehouse_assignments a WHERE a.company_id=w.company_id AND a.user_id=$3 AND a.warehouse_id=w.id)) ORDER BY name`,[s.companyId,s.role,s.userId]),
    tenantRows<Item>(s.companyId,`SELECT id,sku,description,base_uom FROM items WHERE company_id=$1 AND status='active' ORDER BY sku`,[s.companyId]),
  ]):[[],[],[]];
  const message=error==='access'?'You are not assigned to that warehouse. Ask an Owner or Administrator to update Users and access.':error?'The receipt could not be created. Check the receipt number and required details.':null;
  return <div className="app-content"><div className="page-heading"><div><h1>Receiving</h1><p>Expected deliveries, inspection, and guided putaway for your assigned warehouses.</p></div></div>{message&&<div className="form-error">{message}</div>}<div className="form-layout"><section className="panel"><h2>Inbound receipts</h2><table className="data-table"><thead><tr><th>Receipt</th><th>Supplier</th><th>Item</th><th>Expected</th><th>Status</th></tr></thead><tbody>{receipts.length?receipts.map(r=><tr key={r.id}><td><Link className="table-link" href={`/app/receiving/${r.id}`}>{r.receipt_no}</Link></td><td>{r.supplier}</td><td>{r.item}</td><td>{r.expected_quantity} {r.uom}</td><td><span className="badge">{r.status}</span></td></tr>):<tr><td colSpan={5} className="empty-cell">No receipts are available in your assigned warehouses.</td></tr>}</tbody></table></section><aside className="panel"><h2>Create expected receipt</h2>{warehouses.length?<form className="form-stack compact-form" method="post" action="/api/receiving"><div className="field"><label>Receipt number</label><input name="receiptNo" placeholder="GR-0001" required/></div><div className="field"><label>Supplier</label><input name="supplier" required/></div><div className="field"><label>Warehouse</label><select name="warehouseId">{warehouses.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></div><div className="field"><label>Item</label><select name="itemId">{items.map(i=><option key={i.id} value={i.id}>{i.sku} — {i.description}</option>)}</select></div><div className="form-row"><div className="field"><label>Expected quantity</label><input name="expectedQuantity" type="number" min="0.000001" step="any" required/></div><div className="field"><label>Unit</label><input name="uom" placeholder="EA" required/></div></div><div className="field"><label>Expected date</label><input name="expectedDate" type="date"/></div><div className="field"><label>PO/reference</label><input name="externalReference"/></div><button className="button button-primary">Create receipt</button></form>:<div className="knowledge-note"><strong>No assigned warehouse.</strong><p>Ask an Owner or Administrator to approve a warehouse in Users and access before creating or receiving stock.</p></div>}</aside></div></div>;
}
